-- Adicionar grupo muscular de membros inferiores
INSERT INTO app_correcrat.muscle_groups (id, name, icon, color) VALUES
    ('membros_inf', 'Membros Inferiores', 'directions_walk', 'from-violet-500 to-purple-500')
ON CONFLICT (id) DO NOTHING;

-- Exercícios de Membros Inferiores baseados nos GIFs do Supabase Storage
INSERT INTO app_correcrat.exercises (id, name, muscle_group_id, equipment, difficulty, primary_muscle, secondary_muscles, gif_path, description) VALUES
    ('abduc_quad_pe', 'Abdução Quadril em Pé', 'membros_inf', 'corpo', 'iniciante', 'glúteos', ARRAY[]::TEXT[], 'membros inferiores/Abducao de quadril em pe.gif', 'Abdução de quadril em pé.'),
    ('aduc_polia', 'Adução na Polia', 'membros_inf', 'cabo', 'intermediario', 'adutores', ARRAY[]::TEXT[], 'membros inferiores/Aducao na polia.gif', 'Adução na polia.'),
    ('adut_cross', 'Adutora na Tração Cross', 'membros_inf', 'cabo', 'intermediario', 'adutores', ARRAY[]::TEXT[], 'membros inferiores/adutora na tracao do cabo cross.gif', 'Adutora no cross.'),
    ('afundo_livre', 'Afundo Livre', 'membros_inf', 'corpo', 'iniciante', 'pernas', ARRAY['glúteos'], 'membros inferiores/afundo livre.gif', 'Afundo livre.'),
    ('agach_barra_mi', 'Agachamento Barra', 'membros_inf', 'barra', 'intermediario', 'pernas', ARRAY['glúteos'], 'membros inferiores/agachamento barra.gif', 'Agachamento com barra.'),
    ('agach_bulg_barra', 'Agachamento Búlgaro Barra', 'membros_inf', 'barra', 'avancado', 'pernas', ARRAY['glúteos'], 'membros inferiores/agachamento bulgaro com barra.gif', 'Agachamento búlgaro com barra.'),
    ('agach_bulgaro', 'Agachamento Búlgaro', 'membros_inf', 'halteres', 'intermediario', 'pernas', ARRAY['glúteos'], 'membros inferiores/agachamento bulgaro.gif', 'Agachamento búlgaro.'),
    ('agach_halt_uni', 'Agachamento Halteres Uma Perna', 'membros_inf', 'halteres', 'avancado', 'pernas', ARRAY['glúteos'], 'membros inferiores/Agachamento com halteres com uma perna.gif', 'Agachamento unilateral.'),
    ('agach_halteres', 'Agachamento com Halteres', 'membros_inf', 'halteres', 'iniciante', 'pernas', ARRAY['glúteos'], 'membros inferiores/AGACHAMENTO COM HALTERES.gif', 'Agachamento com halteres.'),
    ('agach_hack_mi', 'Agachamento Hack Machine', 'membros_inf', 'maquina', 'intermediario', 'pernas', ARRAY['glúteos'], 'membros inferiores/AGACHAMENTO HACK MACHINE.gif', 'Agachamento hack machine.'),
    ('agach_livre_barra', 'Agachamento Livre Barra', 'membros_inf', 'barra', 'intermediario', 'pernas', ARRAY['glúteos'], 'membros inferiores/Agachamento livre com barra.gif', 'Agachamento livre barra.'),
    ('agach_pes_juntos', 'Agachamento Pés Juntos', 'membros_inf', 'corpo', 'iniciante', 'pernas', ARRAY[]::TEXT[], 'membros inferiores/agachamento livre pes juntos.gif', 'Agachamento pés juntos.'),
    ('agach_maquina_mi', 'Agachamento na Máquina', 'membros_inf', 'maquina', 'iniciante', 'pernas', ARRAY['glúteos'], 'membros inferiores/agachamento na maquina.gif', 'Agachamento na máquina.'),
    ('agach_banco', 'Agachamento no Banco', 'membros_inf', 'corpo', 'iniciante', 'pernas', ARRAY['glúteos'], 'membros inferiores/agachamento no banco.gif', 'Agachamento no banco.'),
    ('agach_cross', 'Agachamento no Cross', 'membros_inf', 'cabo', 'intermediario', 'pernas', ARRAY['glúteos'], 'membros inferiores/agachamento no cross.gif', 'Agachamento no cross.'),
    ('agach_pes_afas', 'Agachamento Pés Afastados', 'membros_inf', 'corpo', 'iniciante', 'pernas', ARRAY['glúteos'], 'membros inferiores/agachamento pes afastados.gif', 'Agachamento pés afastados.'),
    ('agach_sumo_halt2', 'Agachamento Sumô Halteres 2', 'membros_inf', 'halteres', 'intermediario', 'pernas', ARRAY['glúteos', 'adutores'], 'membros inferiores/Agachamento sumo com halteres 2.gif', 'Agachamento sumô halteres.'),
    ('agach_sumo_halt3', 'Agachamento Sumô Halteres', 'membros_inf', 'halteres', 'intermediario', 'pernas', ARRAY['glúteos', 'adutores'], 'membros inferiores/agachamento sumo com halteres.gif', 'Agachamento sumô halteres.'),
    ('agach_sumo_livre', 'Agachamento Sumô Livre', 'membros_inf', 'corpo', 'iniciante', 'pernas', ARRAY['glúteos', 'adutores'], 'membros inferiores/agachamento sumo livre.gif', 'Agachamento sumô livre.'),
    ('agach_sumo_pc', 'Agachamento Sumô Peso Corporal', 'membros_inf', 'corpo', 'iniciante', 'pernas', ARRAY['glúteos', 'adutores'], 'membros inferiores/Agachamento Sumo Peso Corporal.gif', 'Agachamento sumô peso corporal.'),
    ('agach_terra_halt', 'Agachamento Terra Halteres Lado', 'membros_inf', 'halteres', 'intermediario', 'pernas', ARRAY['glúteos'], 'membros inferiores/Agachamento terra com halteres do lado.gif', 'Agachamento terra halteres.'),
    ('cad_abdut_pe', 'Cadeira Abdutora em Pé', 'membros_inf', 'maquina', 'iniciante', 'glúteos', ARRAY[]::TEXT[], 'membros inferiores/CADEIRA ABDUTORA EM Pe.gif', 'Abdutora em pé.'),
    ('cad_abdutora', 'Cadeira Abdutora', 'membros_inf', 'maquina', 'iniciante', 'glúteos', ARRAY[]::TEXT[], 'membros inferiores/CADEIRA-ABDUTORA.gif', 'Cadeira abdutora.'),
    ('cad_adutora', 'Cadeira Adutora', 'membros_inf', 'maquina', 'iniciante', 'adutores', ARRAY[]::TEXT[], 'membros inferiores/cadeira adutora.gif', 'Cadeira adutora.'),
    ('cad_extensora', 'Cadeira Extensora', 'membros_inf', 'maquina', 'iniciante', 'pernas', ARRAY[]::TEXT[], 'membros inferiores/cadeira extensora.gif', 'Cadeira extensora.'),
    ('cad_flex', 'Cadeira Flexora', 'membros_inf', 'maquina', 'iniciante', 'pernas', ARRAY[]::TEXT[], 'membros inferiores/cadeira flex.gif', 'Cadeira flexora.'),
    ('elev_pelv_barra_mi', 'Elevação Pélvica Barra', 'membros_inf', 'barra', 'intermediario', 'glúteos', ARRAY['pernas'], 'membros inferiores/ELEVACAO PELVICA COM BARRA.gif', 'Elevação pélvica barra.'),
    ('elev_pelv_halt', 'Elevação Pélvica Halter', 'membros_inf', 'halteres', 'intermediario', 'glúteos', ARRAY[]::TEXT[], 'membros inferiores/ELEVACAO PELVICA COM HALTER.gif', 'Elevação pélvica halter.'),
    ('elev_pelv_livre', 'Elevação Pélvica Livre', 'membros_inf', 'corpo', 'iniciante', 'glúteos', ARRAY[]::TEXT[], 'membros inferiores/elevacao pelvica livre.gif', 'Elevação pélvica livre.'),
    ('ext_quad_pe_flex', 'Extensão Quadril Pé Joelhos Flexionados', 'membros_inf', 'cabo', 'intermediario', 'glúteos', ARRAY[]::TEXT[], 'membros inferiores/Extensao de quadril em pe com joelhos flexionados.gif', 'Extensão quadril joelhos flexionados.'),
    ('ext_quad_pe_mi', 'Extensão Quadril em Pé', 'membros_inf', 'cabo', 'intermediario', 'glúteos', ARRAY[]::TEXT[], 'membros inferiores/Extensao de Quadril em pe.gif', 'Extensão quadril em pé.'),
    ('ext_quad_polia', 'Extensão Quadril Pé Polia', 'membros_inf', 'cabo', 'intermediario', 'glúteos', ARRAY[]::TEXT[], 'membros inferiores/Extensao de quadril em pe na polia.gif', 'Extensão quadril polia.'),
    ('flex_plantar_pc', 'Flexão Plantar Peso Corporal', 'membros_inf', 'corpo', 'iniciante', 'panturrilhas', ARRAY[]::TEXT[], 'membros inferiores/Flexao Plantar com peso corporal.gif', 'Flexão plantar.'),
    ('flex_joelho_cross', 'Flexão Joelho Pé Cross', 'membros_inf', 'cabo', 'intermediario', 'pernas', ARRAY[]::TEXT[], 'membros inferiores/flex de joelho  em pe no cabo cross.gif', 'Flexão joelho cross.'),
    ('flex_pe_uni', 'Flexora em Pé Unilateral', 'membros_inf', 'maquina', 'intermediario', 'pernas', ARRAY[]::TEXT[], 'membros inferiores/FLEXORA EM Pe UNILATERAL.gif', 'Flexora em pé unilateral.'),
    ('leg_press_mi', 'Leg Press', 'membros_inf', 'maquina', 'iniciante', 'pernas', ARRAY['glúteos'], 'membros inferiores/leg press.gif', 'Leg press.'),
    ('leg_press_horiz_mi', 'Leg Press Horizontal', 'membros_inf', 'maquina', 'iniciante', 'pernas', ARRAY['glúteos'], 'membros inferiores/LEG PRESS HORIZONTAL.gif', 'Leg press horizontal.'),
    ('leg_press_afas', 'Leg Press Pés Afastados', 'membros_inf', 'maquina', 'intermediario', 'pernas', ARRAY['glúteos'], 'membros inferiores/leg press pes afastados.gif', 'Leg press pés afastados.'),
    ('lev_terra_halt_mi', 'Levantamento Terra Halteres', 'membros_inf', 'halteres', 'intermediario', 'costas', ARRAY['glúteos', 'pernas'], 'membros inferiores/levantamento tarra com halteres.gif', 'Levantamento terra halteres.'),
    ('lev_terra_barra_mi', 'Levantamento Terra Barra', 'membros_inf', 'barra', 'avancado', 'costas', ARRAY['glúteos', 'pernas'], 'membros inferiores/levantamento terra com barra.gif', 'Levantamento terra barra.'),
    ('lev_terra_halt_fr', 'Levantamento Terra Halteres Frente', 'membros_inf', 'halteres', 'intermediario', 'costas', ARRAY['glúteos', 'pernas'], 'membros inferiores/Levantamento terrra com halteres frente.gif', 'Levantamento terra halteres frente.'),
    ('mesa_flex_mi', 'Mesa Flexora', 'membros_inf', 'maquina', 'iniciante', 'pernas', ARRAY[]::TEXT[], 'membros inferiores/mesa flex.gif', 'Mesa flexora.'),
    ('mesa_flex_uni_mi', 'Mesa Flexora Unilateral', 'membros_inf', 'maquina', 'intermediario', 'pernas', ARRAY[]::TEXT[], 'membros inferiores/mesa flex unilateral.gif', 'Mesa flexora unilateral.'),
    ('pant_halteres', 'Panturrilha com Halteres', 'membros_inf', 'halteres', 'iniciante', 'panturrilhas', ARRAY[]::TEXT[], 'membros inferiores/PANTURRILHA COM HALTERES.gif', 'Panturrilha halteres.'),
    ('pant_maquina', 'Panturrilha Máquina', 'membros_inf', 'maquina', 'iniciante', 'panturrilhas', ARRAY[]::TEXT[], 'membros inferiores/PANTURRILHA MAQUINA.gif', 'Panturrilha máquina.'),
    ('pant_leg45', 'Panturrilha Leg Press 45', 'membros_inf', 'maquina', 'intermediario', 'panturrilhas', ARRAY[]::TEXT[], 'membros inferiores/PANTURRILHA NO LEG PRESS 45.gif', 'Panturrilha leg press 45.'),
    ('pant_sentado', 'Panturrilha Sentado', 'membros_inf', 'maquina', 'iniciante', 'panturrilhas', ARRAY[]::TEXT[], 'membros inferiores/PANTURRILHA SENTADO.gif', 'Panturrilha sentado.'),
    ('pant_leg_press', 'Panturrilha no Leg Press', 'membros_inf', 'maquina', 'iniciante', 'panturrilhas', ARRAY[]::TEXT[], 'membros inferiores/panturrinha no leg press.gif', 'Panturrilha leg press.'),
    ('passada_frente_bar', 'Passada Frente Barra', 'membros_inf', 'barra', 'intermediario', 'pernas', ARRAY['glúteos'], 'membros inferiores/passada a frente com barra.gif', 'Passada frente barra.'),
    ('passada_frente_halt', 'Passada Frente Halteres', 'membros_inf', 'halteres', 'intermediario', 'pernas', ARRAY['glúteos'], 'membros inferiores/passada a frente com halteres.gif', 'Passada frente halteres.'),
    ('passada_halt', 'Passada com Halteres', 'membros_inf', 'halteres', 'intermediario', 'pernas', ARRAY['glúteos'], 'membros inferiores/passada com halteres.gif', 'Passada halteres.'),
    ('passada_tras_bar', 'Passada Trás Barra', 'membros_inf', 'barra', 'intermediario', 'pernas', ARRAY['glúteos'], 'membros inferiores/passada para tras com barra.gif', 'Passada trás barra.'),
    ('retroc_barra', 'Retrocesso Barra', 'membros_inf', 'barra', 'intermediario', 'pernas', ARRAY['glúteos'], 'membros inferiores/Retrocesso com Barra.gif', 'Retrocesso barra.'),
    ('retroc_halt', 'Retrocesso Halteres', 'membros_inf', 'halteres', 'intermediario', 'pernas', ARRAY['glúteos'], 'membros inferiores/Retrocesso com halteres.gif', 'Retrocesso halteres.'),
    ('afundo_lat_barra', 'Afundo Lateral Barra', 'membros_inf', 'barra', 'intermediario', 'pernas', ARRAY['glúteos'], 'membros inferiores/seitlicher_ausfallschritt_mit_langhantel.gif', 'Afundo lateral barra.'),
    ('stiff_barra_mi', 'Stiff com Barra', 'membros_inf', 'barra', 'intermediario', 'pernas', ARRAY['glúteos', 'lombar'], 'membros inferiores/stiff com barra.gif', 'Stiff barra.'),
    ('stiff_halt_mi', 'Stiff com Halteres', 'membros_inf', 'halteres', 'intermediario', 'pernas', ARRAY['glúteos', 'lombar'], 'membros inferiores/Stiff com Halteres.gif', 'Stiff halteres.'),
    ('stiff_mi', 'Stiff', 'membros_inf', 'barra', 'intermediario', 'pernas', ARRAY['glúteos', 'lombar'], 'membros inferiores/stiff.gif', 'Stiff clássico.'),
    ('stiff_smith', 'Stiff no Smith', 'membros_inf', 'smith', 'intermediario', 'pernas', ARRAY['glúteos', 'lombar'], 'membros inferiores/stiff no smth.gif', 'Stiff smith.'),
    ('stiff_smith_uni', 'Stiff Smith Unilateral', 'membros_inf', 'smith', 'avancado', 'pernas', ARRAY['glúteos', 'lombar'], 'membros inferiores/stiff no smth unilateral.gif', 'Stiff smith unilateral.'),
    ('stiff_uni_kettle', 'Stiff Unilateral Kettlebell', 'membros_inf', 'kettlebell', 'avancado', 'pernas', ARRAY['glúteos', 'lombar'], 'membros inferiores/stiff unilateral com kettibel.gif', 'Stiff unilateral kettlebell.'),
    ('stiff_uni_mi', 'Stiff Unilateral', 'membros_inf', 'halteres', 'avancado', 'pernas', ARRAY['glúteos', 'lombar'], 'membros inferiores/stiff unilateral.gif', 'Stiff unilateral.'),
    ('stiff_uni_medball', 'Stiff Unilateral Medball', 'membros_inf', 'medball', 'avancado', 'pernas', ARRAY['glúteos', 'lombar'], 'membros inferiores/Stiff unil com medball.gif', 'Stiff unilateral medball.'),
    ('agach_profundo', 'Agachamento Profundo Barra', 'membros_inf', 'barra', 'avancado', 'pernas', ARRAY['glúteos'], 'membros inferiores/tiefe_langhantel_kniebeuge.gif', 'Agachamento profundo.')
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, gif_path = EXCLUDED.gif_path, updated_at = NOW();

SELECT COUNT(*) as total_membros_inf FROM app_correcrat.exercises WHERE muscle_group_id = 'membros_inf';
