-- Adicionar grupo muscular de alongamentos
INSERT INTO app_correcrat.muscle_groups (id, name, icon, color) VALUES
    ('alongamentos', 'Alongamentos', 'self_improvement', 'from-cyan-500 to-teal-500')
ON CONFLICT (id) DO NOTHING;

-- Exercícios de Alongamentos baseados nos GIFs do Supabase Storage
INSERT INTO app_correcrat.exercises (id, name, muscle_group_id, equipment, difficulty, primary_muscle, secondary_muscles, gif_path, description) VALUES
    ('along_1', 'Alongamento 1', 'alongamentos', 'corpo', 'iniciante', 'alongamento', ARRAY[]::TEXT[], 'alongamentos/ALONGAMENTO 1.gif', 'Alongamento geral.'),
    ('along_2', 'Alongamento 2', 'alongamentos', 'corpo', 'iniciante', 'alongamento', ARRAY[]::TEXT[], 'alongamentos/ALONGAMENTO 2.gif', 'Alongamento geral.'),
    ('along_3', 'Alongamento 3', 'alongamentos', 'corpo', 'iniciante', 'alongamento', ARRAY[]::TEXT[], 'alongamentos/ALONGAMENTO 3.gif', 'Alongamento geral.'),
    ('along_4', 'Alongamento 4', 'alongamentos', 'corpo', 'iniciante', 'alongamento', ARRAY[]::TEXT[], 'alongamentos/ALONGAMENTO 4.gif', 'Alongamento geral.'),
    ('along_5', 'Alongamento 5', 'alongamentos', 'corpo', 'iniciante', 'alongamento', ARRAY[]::TEXT[], 'alongamentos/ALONGAMENTO 5.gif', 'Alongamento geral.'),
    ('along_6', 'Alongamento 6', 'alongamentos', 'corpo', 'iniciante', 'alongamento', ARRAY[]::TEXT[], 'alongamentos/ALONGAMENTO 6.gif', 'Alongamento geral.'),
    ('along_7', 'Alongamento 7', 'alongamentos', 'corpo', 'iniciante', 'alongamento', ARRAY[]::TEXT[], 'alongamentos/ALONGAMENTO 7.gif', 'Alongamento geral.'),
    ('along_8', 'Alongamento 8', 'alongamentos', 'corpo', 'iniciante', 'alongamento', ARRAY[]::TEXT[], 'alongamentos/ALONGAMENTO 8.gif', 'Alongamento geral.'),
    ('along_9', 'Alongamento 9', 'alongamentos', 'corpo', 'iniciante', 'alongamento', ARRAY[]::TEXT[], 'alongamentos/ALONGAMENTO 9.gif', 'Alongamento geral.'),
    ('along_10', 'Alongamento 10', 'alongamentos', 'corpo', 'iniciante', 'alongamento', ARRAY[]::TEXT[], 'alongamentos/ALONGAMENTO 10.gif', 'Alongamento geral.'),
    ('along_11', 'Alongamento 11', 'alongamentos', 'corpo', 'iniciante', 'alongamento', ARRAY[]::TEXT[], 'alongamentos/ALONGAMENTO 11.gif', 'Alongamento geral.'),
    ('along_12', 'Alongamento 12', 'alongamentos', 'corpo', 'iniciante', 'alongamento', ARRAY[]::TEXT[], 'alongamentos/ALONGAMENTO 12.gif', 'Alongamento geral.'),
    ('along_13', 'Alongamento 13', 'alongamentos', 'corpo', 'iniciante', 'alongamento', ARRAY[]::TEXT[], 'alongamentos/ALONGAMENTO 13.gif', 'Alongamento geral.'),
    ('along_14', 'Alongamento 14', 'alongamentos', 'corpo', 'iniciante', 'alongamento', ARRAY[]::TEXT[], 'alongamentos/ALONGAMENTO 14.gif', 'Alongamento geral.'),
    ('along_15', 'Alongamento 15', 'alongamentos', 'corpo', 'iniciante', 'alongamento', ARRAY[]::TEXT[], 'alongamentos/ALONGAMENTO 15.gif', 'Alongamento geral.'),
    ('along_16', 'Alongamento 16', 'alongamentos', 'corpo', 'iniciante', 'alongamento', ARRAY[]::TEXT[], 'alongamentos/ALONGAMENTO 16.gif', 'Alongamento geral.'),
    ('along_17', 'Alongamento 17', 'alongamentos', 'corpo', 'iniciante', 'alongamento', ARRAY[]::TEXT[], 'alongamentos/ALONGAMENTO 17.gif', 'Alongamento geral.'),
    ('along_18', 'Alongamento 18', 'alongamentos', 'corpo', 'iniciante', 'alongamento', ARRAY[]::TEXT[], 'alongamentos/ALONGAMENTO 18.gif', 'Alongamento geral.'),
    ('along_19', 'Alongamento 19', 'alongamentos', 'corpo', 'iniciante', 'alongamento', ARRAY[]::TEXT[], 'alongamentos/ALONGAMENTO 19.gif', 'Alongamento geral.'),
    ('along_20', 'Alongamento 20', 'alongamentos', 'corpo', 'iniciante', 'alongamento', ARRAY[]::TEXT[], 'alongamentos/ALONGAMENTO 20.gif', 'Alongamento geral.'),
    ('along_21', 'Alongamento 21', 'alongamentos', 'corpo', 'iniciante', 'alongamento', ARRAY[]::TEXT[], 'alongamentos/ALONGAMENTO 21.gif', 'Alongamento geral.'),
    ('along_22', 'Alongamento 22', 'alongamentos', 'corpo', 'iniciante', 'alongamento', ARRAY[]::TEXT[], 'alongamentos/ALONGAMENTO 22.gif', 'Alongamento geral.'),
    ('along_23', 'Alongamento 23', 'alongamentos', 'corpo', 'iniciante', 'alongamento', ARRAY[]::TEXT[], 'alongamentos/ALONGAMENTO 23.gif', 'Alongamento geral.'),
    ('along_24', 'Alongamento 24', 'alongamentos', 'corpo', 'iniciante', 'alongamento', ARRAY[]::TEXT[], 'alongamentos/ALONGAMENTO 24.gif', 'Alongamento geral.'),
    ('along_25', 'Alongamento 25', 'alongamentos', 'corpo', 'iniciante', 'alongamento', ARRAY[]::TEXT[], 'alongamentos/ALONGAMENTO 25.gif', 'Alongamento geral.'),
    ('along_assist_rev', 'Alongamento Assistido Reverso Peitoral Ombro', 'alongamentos', 'corpo', 'iniciante', 'alongamento', ARRAY['peitoral', 'ombros'], 'alongamentos/Alongamento assistido reverso (peitoral e ombro).gif', 'Alongamento peitoral e ombro.'),
    ('along_biceps', 'Alongamento Bíceps', 'alongamentos', 'corpo', 'iniciante', 'alongamento', ARRAY['bíceps'], 'alongamentos/ALONGAMENTO BICEPS.gif', 'Alongamento bíceps.'),
    ('along_biceps2', 'Alongamento Bíceps 2', 'alongamentos', 'corpo', 'iniciante', 'alongamento', ARRAY['bíceps'], 'alongamentos/ALONGAMENTO BICEPS 2.gif', 'Alongamento bíceps variação.'),
    ('along_borboleta', 'Alongamento Borboleta', 'alongamentos', 'corpo', 'iniciante', 'alongamento', ARRAY['adutores'], 'alongamentos/Alongamento Borboleta.gif', 'Alongamento borboleta.'),
    ('along_esfinge', 'Alongamento da Esfinge', 'alongamentos', 'corpo', 'iniciante', 'alongamento', ARRAY['lombar'], 'alongamentos/Alongamento da Esfinge.gif', 'Postura esfinge.'),
    ('along_pant_agach', 'Alongamento Panturrilha Agachado', 'alongamentos', 'corpo', 'iniciante', 'alongamento', ARRAY['panturrilhas'], 'alongamentos/Alongamento da panturrilha agachado.gif', 'Alongamento panturrilha agachado.'),
    ('along_pant_calc', 'Alongamento Panturrilha Calcanhar', 'alongamentos', 'corpo', 'iniciante', 'alongamento', ARRAY['panturrilhas'], 'alongamentos/Alongamento da panturrilha com descida do calcanhar.gif', 'Alongamento panturrilha calcanhar.'),
    ('along_costas_sup', 'Alongamento Costas Superior', 'alongamentos', 'corpo', 'iniciante', 'alongamento', ARRAY['costas'], 'alongamentos/Alongamento da parte superior das costas.gif', 'Alongamento costas superior.'),
    ('along_costas_rolo', 'Alongamento Costas Rolo Espuma', 'alongamentos', 'rolo', 'iniciante', 'alongamento', ARRAY['costas'], 'alongamentos/Alongamento das Costas com Rolo de Espuma.gif', 'Alongamento costas rolo.'),
    ('along_isquio_deit', 'Alongamento Isquiotibiais Deitado', 'alongamentos', 'corpo', 'iniciante', 'alongamento', ARRAY['pernas'], 'alongamentos/Alongamento de Isquiotibiais deitado.gif', 'Alongamento isquiotibiais.'),
    ('along_pant_corda', 'Alongamento Panturrilha Corda', 'alongamentos', 'corda', 'iniciante', 'alongamento', ARRAY['panturrilhas'], 'alongamentos/Alongamento de Panturrilha com Corda.gif', 'Alongamento panturrilha corda.'),
    ('along_pant_estic', 'Alongamento Panturrilha Esticada', 'alongamentos', 'corpo', 'iniciante', 'alongamento', ARRAY['panturrilhas'], 'alongamentos/Alongamento de panturrilha com uma perna esticada.gif', 'Alongamento panturrilha esticada.'),
    ('along_pant_uma', 'Alongamento Panturrilha Uma Perna', 'alongamentos', 'corpo', 'iniciante', 'alongamento', ARRAY['panturrilhas'], 'alongamentos/Alongamento de panturrilha com uma perna.gif', 'Alongamento panturrilha uma perna.'),
    ('along_pant_passo', 'Alongamento Panturrilha Passo Largo', 'alongamentos', 'corpo', 'iniciante', 'alongamento', ARRAY['panturrilhas'], 'alongamentos/Alongamento de panturrilha em passo largo.gif', 'Alongamento panturrilha passo largo.'),
    ('along_pant_parede', 'Alongamento Panturrilha Parede', 'alongamentos', 'corpo', 'iniciante', 'alongamento', ARRAY['panturrilhas'], 'alongamentos/Alongamento de panturrilha na parede.gif', 'Alongamento panturrilha parede.'),
    ('along_pernas_duplo', 'Alongamento Pernas Duplo', 'alongamentos', 'corpo', 'iniciante', 'alongamento', ARRAY['pernas'], 'alongamentos/Alongamento de Pernas Duplo.gif', 'Alongamento pernas duplo.'),
    ('along_punho', 'Alongamento de Punho', 'alongamentos', 'corpo', 'iniciante', 'alongamento', ARRAY['antebraço'], 'alongamentos/Alongamento de Punho.gif', 'Alongamento punho.'),
    ('along_quadril_90', 'Alongamento Quadril 90-90', 'alongamentos', 'corpo', 'intermediario', 'alongamento', ARRAY['glúteos'], 'alongamentos/Alongamento de quadril 90-90.gif', 'Alongamento quadril 90-90.'),
    ('along_ulnar', 'Alongamento Desviador Ulnar', 'alongamentos', 'corpo', 'iniciante', 'alongamento', ARRAY['antebraço'], 'alongamentos/Alongamento do desviador ulnar e extensor do punho.gif', 'Alongamento ulnar.'),
    ('along_manguito', 'Alongamento Manguito Rotador', 'alongamentos', 'corpo', 'iniciante', 'alongamento', ARRAY['ombros'], 'alongamentos/Alongamento do manguito rotador.gif', 'Alongamento manguito.'),
    ('along_ombro_toalha', 'Alongamento Ombro Toalha', 'alongamentos', 'toalha', 'iniciante', 'alongamento', ARRAY['ombros'], 'alongamentos/Alongamento do ombro com toalha.gif', 'Alongamento ombro toalha.'),
    ('along_peito_rolo', 'Alongamento Peito Rolo Espuma', 'alongamentos', 'rolo', 'iniciante', 'alongamento', ARRAY['peitoral'], 'alongamentos/Alongamento do peito com rolo de espuma.gif', 'Alongamento peito rolo.'),
    ('along_peito_ombro', 'Alongamento Peito Ombros', 'alongamentos', 'corpo', 'iniciante', 'alongamento', ARRAY['peitoral', 'ombros'], 'alongamentos/Alongamento do Peito e Parte Frontal dos Ombros.gif', 'Alongamento peito ombros.'),
    ('along_peito_porta', 'Alongamento Peitoral Porta', 'alongamentos', 'corpo', 'iniciante', 'alongamento', ARRAY['peitoral'], 'alongamentos/Alongamento do peitoral e do ombro na porta.gif', 'Alongamento peitoral porta.'),
    ('along_peito_rev', 'Alongamento Peitoral Reverso', 'alongamentos', 'corpo', 'iniciante', 'alongamento', ARRAY['peitoral'], 'alongamentos/Alongamento do peitoral reverso.gif', 'Alongamento peitoral reverso.'),
    ('along_piriforme_sent', 'Alongamento Piriforme Sentado', 'alongamentos', 'corpo', 'iniciante', 'alongamento', ARRAY['glúteos'], 'alongamentos/Alongamento do Piriforme Sentado.gif', 'Alongamento piriforme sentado.'),
    ('along_adut_ajoel', 'Alongamento Adutores Ajoelhado', 'alongamentos', 'corpo', 'iniciante', 'alongamento', ARRAY['adutores'], 'alongamentos/Alongamento dos Adutores com a Perna Estendida ajoelhado.gif', 'Alongamento adutores ajoelhado.'),
    ('along_adut_rolo', 'Alongamento Adutores Rolo', 'alongamentos', 'rolo', 'iniciante', 'alongamento', ARRAY['adutores'], 'alongamentos/Alongamento dos adutores da coxa com rolo de espuma.gif', 'Alongamento adutores rolo.'),
    ('along_adut_sent', 'Alongamento Adutores Sentado', 'alongamentos', 'corpo', 'iniciante', 'alongamento', ARRAY['adutores'], 'alongamentos/Alongamento dos adutores sentado.gif', 'Alongamento adutores sentado.'),
    ('along_flex_quadril', 'Alongamento Flexores Quadril', 'alongamentos', 'corpo', 'iniciante', 'alongamento', ARRAY['quadril'], 'alongamentos/Alongamento dos flexores de quadril ajoelhado.gif', 'Alongamento flexores quadril.'),
    ('along_isquio_sent', 'Alongamento Isquiotibiais Sentado', 'alongamentos', 'corpo', 'iniciante', 'alongamento', ARRAY['pernas'], 'alongamentos/Alongamento dos Isquiotibiais Sentado.gif', 'Alongamento isquiotibiais sentado.'),
    ('along_tibial', 'Alongamento Tibial Posterior', 'alongamentos', 'corpo', 'iniciante', 'alongamento', ARRAY['pernas'], 'alongamentos/Alongamento do tibial posterior.gif', 'Alongamento tibial.'),
    ('along_iliotibial', 'Alongamento Trato Iliotibial', 'alongamentos', 'rolo', 'iniciante', 'alongamento', ARRAY['pernas'], 'alongamentos/Alongamento do trato iliotibial com rolo de espuma.gif', 'Alongamento iliotibial.'),
    ('along_lat_coxa', 'Alongamento Lateral Coxa', 'alongamentos', 'corpo', 'iniciante', 'alongamento', ARRAY['adutores'], 'alongamentos/Alongamento Lateral da Parte Interna da Coxa.gif', 'Alongamento lateral coxa.'),
    ('along_parede_canto', 'Alongamento Parede Canto', 'alongamentos', 'corpo', 'iniciante', 'alongamento', ARRAY['peitoral'], 'alongamentos/Alongamento na parede do canto.gif', 'Alongamento parede canto.'),
    ('along_perna', 'Alongamento Perna', 'alongamentos', 'corpo', 'iniciante', 'alongamento', ARRAY['pernas'], 'alongamentos/ALONGAMENTO PERNA.gif', 'Alongamento perna.'),
    ('along_piriforme', 'Alongamento Piriforme', 'alongamentos', 'corpo', 'iniciante', 'alongamento', ARRAY['glúteos'], 'alongamentos/Alongamento Piriforme.gif', 'Alongamento piriforme.'),
    ('along_quadriceps', 'Alongamento Quadríceps', 'alongamentos', 'corpo', 'iniciante', 'alongamento', ARRAY['pernas'], 'alongamentos/ALONGAMENTO QUADRICEPS.gif', 'Alongamento quadríceps.'),
    ('along_rev_assist', 'Alongamento Reverso Assistido', 'alongamentos', 'corpo', 'iniciante', 'alongamento', ARRAY['peitoral', 'ombros'], 'alongamentos/Alongamento reverso assistido (peito e ombro).gif', 'Alongamento reverso assistido.'),
    ('along_pulso_rev', 'Alongamento Reverso Pulso', 'alongamentos', 'corpo', 'iniciante', 'alongamento', ARRAY['antebraço'], 'alongamentos/Alongamento Reverso de Pulso.gif', 'Alongamento reverso pulso.'),
    ('along_pant_sent', 'Alongamento Panturrilha Sentado', 'alongamentos', 'corpo', 'iniciante', 'alongamento', ARRAY['panturrilhas'], 'alongamentos/Alongamento Sentado para a Panturrilha com Perna Esticada.gif', 'Alongamento panturrilha sentado.'),
    ('along_ombros', 'Alongamento Ombros', 'alongamentos', 'corpo', 'iniciante', 'alongamento', ARRAY['ombros'], 'alongamentos/ALONGAMENTOS OMBROS.gif', 'Alongamento ombros.'),
    ('along_triceps', 'Alongamento Tríceps', 'alongamentos', 'corpo', 'iniciante', 'alongamento', ARRAY['tríceps'], 'alongamentos/ALONGAMENTO TRICEPS.gif', 'Alongamento tríceps.'),
    ('catavento', 'Catavento Corporal', 'alongamentos', 'corpo', 'iniciante', 'alongamento', ARRAY[]::TEXT[], 'alongamentos/Catavento corporal.gif', 'Catavento corporal.'),
    ('joelho_alt_peito', 'Joelho Alternado Peito', 'alongamentos', 'corpo', 'iniciante', 'alongamento', ARRAY['glúteos'], 'alongamentos/Joelho Alternado no Peito.gif', 'Joelho alternado peito.'),
    ('cobra_abd', 'Postura Cobra Alongamento Abdominal', 'alongamentos', 'corpo', 'iniciante', 'alongamento', ARRAY['abdômen'], 'alongamentos/Postura da Cobra - Alongamento Abdominal.gif', 'Postura cobra.'),
    ('virilha_sent', 'Postura Virilha Sentada', 'alongamentos', 'corpo', 'iniciante', 'alongamento', ARRAY['adutores'], 'alongamentos/Postura da Virilha Sentada.gif', 'Postura virilha sentada.'),
    ('meio_sapo', 'Postura Meio Sapo', 'alongamentos', 'corpo', 'intermediario', 'alongamento', ARRAY['quadríceps'], 'alongamentos/Postura de meio sapo.gif', 'Postura meio sapo.'),
    ('peixe', 'Postura Peixe', 'alongamentos', 'corpo', 'intermediario', 'alongamento', ARRAY['peitoral'], 'alongamentos/Postura de peixe.gif', 'Postura peixe.'),
    ('arco', 'Postura Arco', 'alongamentos', 'corpo', 'intermediario', 'alongamento', ARRAY['abdômen'], 'alongamentos/Postura do Arco.gif', 'Postura arco.'),
    ('arco_osc', 'Postura Arco Oscilante', 'alongamentos', 'corpo', 'avancado', 'alongamento', ARRAY['abdômen'], 'alongamentos/Postura do Arco Oscilante.gif', 'Postura arco oscilante.'),
    ('sapo', 'Postura Sapo', 'alongamentos', 'corpo', 'intermediario', 'alongamento', ARRAY['adutores'], 'alongamentos/Postura do sapo.gif', 'Postura sapo.'),
    ('puxada_escapular', 'Puxada Escapular Barra', 'alongamentos', 'corpo', 'intermediario', 'alongamento', ARRAY['costas'], 'alongamentos/Puxada escapular na barra fixa.gif', 'Puxada escapular.'),
    ('rolo_isquio', 'Rolagem Espuma Isquiotibiais', 'alongamentos', 'rolo', 'iniciante', 'alongamento', ARRAY['pernas'], 'alongamentos/Rolagem de espuma para isquiotibiais.gif', 'Rolo isquiotibiais.'),
    ('rolo_costas', 'Rolamento Espuma Costas', 'alongamentos', 'rolo', 'iniciante', 'alongamento', ARRAY['costas'], 'alongamentos/Rolamento de espuma nas costas.gif', 'Rolo costas.'),
    ('rolo_romboides', 'Rolamento Espuma Romboides', 'alongamentos', 'rolo', 'iniciante', 'alongamento', ARRAY['costas'], 'alongamentos/Rolamento de espuma nos romboides.gif', 'Rolo romboides.'),
    ('rolo_pant', 'Rolamento Espuma Panturrilhas', 'alongamentos', 'rolo', 'iniciante', 'alongamento', ARRAY['panturrilhas'], 'alongamentos/Rolamento de Espuma para Panturrilhas.gif', 'Rolo panturrilhas.'),
    ('rolando_bola', 'Rolando Como Bola', 'alongamentos', 'corpo', 'iniciante', 'alongamento', ARRAY['costas'], 'alongamentos/Rolando como uma Bola.gif', 'Rolando bola.'),
    ('rolo_ombro_post', 'Rolo Espuma Ombro Posterior', 'alongamentos', 'rolo', 'iniciante', 'alongamento', ARRAY['ombros'], 'alongamentos/Rolo de espuma ombro posterior.gif', 'Rolo ombro posterior.'),
    ('rolo_plantar', 'Rolo Espuma Fascite Plantar', 'alongamentos', 'rolo', 'iniciante', 'alongamento', ARRAY['pés'], 'alongamentos/Rolo de espuma para fascite plantar.gif', 'Rolo fascite plantar.'),
    ('rolo_ombro_peito', 'Rolo Espuma Ombro Peito', 'alongamentos', 'rolo', 'iniciante', 'alongamento', ARRAY['peitoral', 'ombros'], 'alongamentos/Rolo de espuma para ombro e peito frontal.gif', 'Rolo ombro peito.'),
    ('superman_along', 'Superman Alongamento', 'alongamentos', 'corpo', 'iniciante', 'alongamento', ARRAY['lombar'], 'alongamentos/Superman.gif', 'Superman alongamento.')
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, gif_path = EXCLUDED.gif_path, updated_at = NOW();

SELECT COUNT(*) as total_alongamentos FROM app_correcrat.exercises WHERE muscle_group_id = 'alongamentos';
