-- Exercícios de Bíceps baseados nos GIFs do Supabase Storage
-- Total: 69 exercícios

INSERT INTO app_correcrat.exercises (id, name, muscle_group_id, equipment, difficulty, primary_muscle, secondary_muscles, gif_path, description) VALUES
    ('biceps_concentrado_cross', 'Bíceps Concentrado Unilateral Cross', 'biceps', 'cabo', 'intermediario', 'bíceps', ARRAY['antebraço'], 'Biceps/biceps concentrado unilateral no cross.gif', 'Rosca concentrada unilateral no cross over.'),
    ('biceps_polia_alta_dupla', 'Bíceps Polia Alta Dupla', 'biceps', 'cabo', 'intermediario', 'bíceps', ARRAY['antebraço'], 'Biceps/biceps polia alta dupla.gif', 'Rosca dupla com polias altas.'),
    ('biceps_uni_scott_cross', 'Bíceps Unilateral Banco Scott Cross', 'biceps', 'cabo', 'intermediario', 'bíceps', ARRAY[]::TEXT[], 'Biceps/biceps unilateral com banco scort no cross.gif', 'Scott unilateral no cross.'),
    ('biceps_unilateral_cross', 'Bíceps Unilateral Cross', 'biceps', 'cabo', 'intermediario', 'bíceps', ARRAY[]::TEXT[], 'Biceps/biceps unilateral cross.gif', 'Rosca unilateral no cross over.'),
    ('biceps_uni_polia_alta', 'Bíceps Unilateral Polia Alta', 'biceps', 'cabo', 'intermediario', 'bíceps', ARRAY[]::TEXT[], 'Biceps/biceps unilateral polia alta cross.gif', 'Rosca unilateral polia alta.'),
    ('rosca_alt_biarticular', 'Rosca Alternada Aparelho Biarticular', 'biceps', 'maquina', 'iniciante', 'bíceps', ARRAY[]::TEXT[], 'Biceps/rosca alternada aparelho biarticular.gif', 'Rosca alternada na máquina biarticular.'),
    ('rosca_alt_barra', 'Rosca Alternada com Barra', 'biceps', 'barra', 'iniciante', 'bíceps', ARRAY['antebraço'], 'Biceps/Rosca alternada com barra.gif', 'Rosca alternada com barra.'),
    ('rosca_alt_giro', 'Rosca Alternada com Giro', 'biceps', 'halteres', 'intermediario', 'bíceps', ARRAY['antebraço'], 'Biceps/rosca alternada com giro.gif', 'Rosca alternada com supinação.'),
    ('rosca_alt_sentado', 'Rosca Alternada Sentado', 'biceps', 'halteres', 'iniciante', 'bíceps', ARRAY['antebraço'], 'Biceps/Rosca alternada com halteres sentado.gif', 'Rosca alternada sentado no banco.'),
    ('rosca_alt_neutra', 'Rosca Alternada Pegada Neutra', 'biceps', 'halteres', 'iniciante', 'bíceps', ARRAY['antebraço'], 'Biceps/rosca alternada pegada neutra.gif', 'Rosca martelo alternada.'),
    ('rosca_alt_neutra_sent', 'Rosca Alternada Neutra Sentado', 'biceps', 'halteres', 'iniciante', 'bíceps', ARRAY['antebraço'], 'Biceps/rosca alternada pegada neutra sentado no banco.gif', 'Rosca martelo alternada sentado.'),
    ('rosca_bilateral_incl', 'Rosca Bilateral Cabo Inclinado', 'biceps', 'cabo', 'intermediario', 'bíceps', ARRAY[]::TEXT[], 'Biceps/Rosca Bilateral com Cabo em Banco Inclinado.gif', 'Rosca bilateral no banco inclinado com cabo.'),
    ('rosca_barra2', 'Rosca com Barra', 'biceps', 'barra', 'iniciante', 'bíceps', ARRAY['antebraço'], 'Biceps/Rosca com barra.gif', 'Rosca direta com barra.'),
    ('rosca_halteres2', 'Rosca com Halteres', 'biceps', 'halteres', 'iniciante', 'bíceps', ARRAY['antebraço'], 'Biceps/Rosca com halteres.gif', 'Rosca direta com halteres.'),
    ('rosca_colete_scott', 'Rosca Halteres Colete Scott', 'biceps', 'halteres', 'intermediario', 'bíceps', ARRAY[]::TEXT[], 'Biceps/Rosca com halteres no colete scott.gif', 'Rosca no colete scott.'),
    ('rosca_polia_alta2', 'Rosca com Polia Alta', 'biceps', 'cabo', 'intermediario', 'bíceps', ARRAY[]::TEXT[], 'Biceps/Rosca com Polia Alta.gif', 'Rosca com polia alta.'),
    ('rosca_concentrada1', 'Rosca Concentrada Variação 1', 'biceps', 'halteres', 'intermediario', 'bíceps', ARRAY[]::TEXT[], 'Biceps/Rosca concentrada(1).gif', 'Rosca concentrada variação.'),
    ('rosca_concentrada2', 'Rosca Concentrada Variação 2', 'biceps', 'halteres', 'intermediario', 'bíceps', ARRAY[]::TEXT[], 'Biceps/Rosca Concentrada 2.gif', 'Rosca concentrada variação 2.'),
    ('rosca_concentrada_cabo', 'Rosca Concentrada com Cabo', 'biceps', 'cabo', 'intermediario', 'bíceps', ARRAY[]::TEXT[], 'Biceps/Rosca concentrada com cabo.gif', 'Rosca concentrada no cabo.'),
    ('rosca_conc_fechada', 'Rosca Concentrada Pegada Fechada', 'biceps', 'halteres', 'intermediario', 'bíceps', ARRAY[]::TEXT[], 'Biceps/Rosca Concentrada com Pegada Fechada Sentado.gif', 'Rosca concentrada pegada fechada.'),
    ('rosca_concentrada3', 'Rosca Concentrada', 'biceps', 'halteres', 'intermediario', 'bíceps', ARRAY[]::TEXT[], 'Biceps/Rosca Concentrada.gif', 'Rosca concentrada clássica.'),
    ('rosca_conc_uni_cabo', 'Rosca Concentrada Unilateral Cabo', 'biceps', 'cabo', 'intermediario', 'bíceps', ARRAY[]::TEXT[], 'Biceps/Rosca concentrada unilateral com cabo.gif', 'Rosca concentrada unilateral no cabo.'),
    ('rosca_conc_declinado', 'Rosca Concentrada Banco Declinado', 'biceps', 'halteres', 'avancado', 'bíceps', ARRAY[]::TEXT[], 'Biceps/rosca consentrada unilateral  no banco declinado.gif', 'Rosca concentrada no banco declinado.'),
    ('rosca_direta_aberta', 'Rosca Direta Pegada Aberta', 'biceps', 'barra', 'iniciante', 'bíceps', ARRAY['antebraço'], 'Biceps/rosca dierta pegada aberta.gif', 'Rosca direta com pegada aberta.'),
    ('rosca_direta_fechada', 'Rosca Direta Pegada Fechada', 'biceps', 'barra', 'iniciante', 'bíceps', ARRAY['antebraço'], 'Biceps/rosca dierta pegada fechada.gif', 'Rosca direta com pegada fechada.'),
    ('rosca_apoiada_w', 'Rosca Apoiada Banco Barra W', 'biceps', 'barra', 'intermediario', 'bíceps', ARRAY[]::TEXT[], 'Biceps/rosca direta apaiada no banco barra W.gif', 'Rosca apoiada no banco com barra W.'),
    ('rosca_fechada_sentado', 'Rosca Direta Fechada Sentado', 'biceps', 'barra', 'intermediario', 'bíceps', ARRAY[]::TEXT[], 'Biceps/rosca direta barra pegada fechada sentado no banco.gif', 'Rosca direta pegada fechada sentado.'),
    ('rosca_barra_w2', 'Rosca Direta Barra W', 'biceps', 'barra', 'iniciante', 'bíceps', ARRAY['antebraço'], 'Biceps/rosca direta barra W.gif', 'Rosca direta com barra W.'),
    ('rosca_w_sentado', 'Rosca Barra W Sentado', 'biceps', 'barra', 'iniciante', 'bíceps', ARRAY[]::TEXT[], 'Biceps/rosca direta barra W sentado banco.gif', 'Rosca barra W sentado no banco.'),
    ('rosca_barra_deitado', 'Rosca Barra Deitado Banco Alto', 'biceps', 'barra', 'intermediario', 'bíceps', ARRAY[]::TEXT[], 'Biceps/Rosca Direta com Barra deitado em Banco Alto.gif', 'Rosca deitado no banco alto.'),
    ('rosca_barra_fechada2', 'Rosca Barra Pegada Fechada', 'biceps', 'barra', 'iniciante', 'bíceps', ARRAY[]::TEXT[], 'Biceps/Rosca Direta com Barra em Pegada Fechada.gif', 'Rosca direta pegada fechada.'),
    ('rosca_direta_barra', 'Rosca Direta com Barra', 'biceps', 'barra', 'iniciante', 'bíceps', ARRAY['antebraço'], 'Biceps/Rosca Direta com Barra.gif', 'Rosca direta clássica.'),
    ('rosca_barra_colete', 'Rosca Barra Colete Scott', 'biceps', 'barra', 'intermediario', 'bíceps', ARRAY[]::TEXT[], 'Biceps/Rosca Direta com Barra no colete scott.gif', 'Rosca no colete scott com barra.'),
    ('rosca_direta_w', 'Rosca Direta Barra W Clássica', 'biceps', 'barra', 'iniciante', 'bíceps', ARRAY['antebraço'], 'Biceps/Rosca direta com barra w.gif', 'Rosca direta barra W clássica.'),
    ('rosca_cabo_deitado', 'Rosca Cabo Deitado', 'biceps', 'cabo', 'intermediario', 'bíceps', ARRAY[]::TEXT[], 'Biceps/Rosca Direta com Cabo deitado.gif', 'Rosca deitado no cabo.'),
    ('rosca_deitado_cross', 'Rosca Deitado Banco Reto Cross', 'biceps', 'cabo', 'intermediario', 'bíceps', ARRAY[]::TEXT[], 'Biceps/rosca direta deitado no banco reto no cross.gif', 'Rosca deitado no cross.'),
    ('rosca_scott2', 'Rosca Direta no Banco Scott', 'biceps', 'barra', 'intermediario', 'bíceps', ARRAY[]::TEXT[], 'Biceps/rosca  direta no banco scort.gif', 'Rosca no banco scott.'),
    ('rosca_cross_w', 'Rosca Cross Barra W', 'biceps', 'cabo', 'intermediario', 'bíceps', ARRAY[]::TEXT[], 'Biceps/rosca direta no cross barra W.gif', 'Rosca no cross com barra W.'),
    ('rosca_fechada_w', 'Rosca Pegada Fechada Barra W', 'biceps', 'barra', 'intermediario', 'bíceps', ARRAY[]::TEXT[], 'Biceps/rosca direta pegada fechada barra W.gif', 'Rosca pegada fechada barra W.'),
    ('rosca_invertida_w', 'Rosca Pegada Invertida Barra W', 'biceps', 'barra', 'intermediario', 'bíceps', ARRAY['antebraço'], 'Biceps/rosca direta pegada invertida barra W.gif', 'Rosca pronada barra W.'),
    ('rosca_inversa_w', 'Rosca Inversa com Barra W', 'biceps', 'barra', 'intermediario', 'bíceps', ARRAY['antebraço'], 'Biceps/Rosca inversa com barra W.gif', 'Rosca inversa para braquiorradial.'),
    ('rosca_inversa_halt', 'Rosca Inversa com Halteres', 'biceps', 'halteres', 'intermediario', 'bíceps', ARRAY['antebraço'], 'Biceps/Rosca Inversa com Halteres.gif', 'Rosca inversa com halteres.'),
    ('rosca_martelo_corda', 'Rosca Martelo com Corda', 'biceps', 'cabo', 'iniciante', 'bíceps', ARRAY['antebraço'], 'Biceps/Rosca martelo com corda.gif', 'Rosca martelo no cabo com corda.'),
    ('rosca_martelo_scott', 'Rosca Martelo Banco Scott', 'biceps', 'halteres', 'intermediario', 'bíceps', ARRAY[]::TEXT[], 'Biceps/Rosca martelo com halteres no banco scott.gif', 'Rosca martelo no banco scott.'),
    ('rosca_martelo_colete', 'Rosca Martelo Colete Scott', 'biceps', 'halteres', 'intermediario', 'bíceps', ARRAY[]::TEXT[], 'Biceps/Rosca martelo com halter no colete scott.gif', 'Rosca martelo no colete scott.'),
    ('rosca_martelo2', 'Rosca Martelo', 'biceps', 'halteres', 'iniciante', 'bíceps', ARRAY['antebraço'], 'Biceps/Rosca martelo.gif', 'Rosca martelo clássica.'),
    ('rosca_martelo_sent', 'Rosca Martelo Sentada', 'biceps', 'halteres', 'iniciante', 'bíceps', ARRAY['antebraço'], 'Biceps/Rosca martelo sentada.gif', 'Rosca martelo sentado.'),
    ('rosca_neutra_halt', 'Rosca Neutra com Halteres', 'biceps', 'halteres', 'iniciante', 'bíceps', ARRAY['antebraço'], 'Biceps/rosca neutra com halteres.gif', 'Rosca neutra em pé.'),
    ('rosca_neutra_sentado', 'Rosca Neutra Sentado', 'biceps', 'halteres', 'iniciante', 'bíceps', ARRAY['antebraço'], 'Biceps/rosca neutra com halteres sentado no banco.gif', 'Rosca neutra sentado no banco.'),
    ('rosca_neutra_scott_ap', 'Rosca Neutra Scott Aparelho', 'biceps', 'maquina', 'intermediario', 'bíceps', ARRAY[]::TEXT[], 'Biceps/rosca neutra no banco scort aparelho.gif', 'Rosca neutra no scott máquina.'),
    ('rosca_neutra_uni_scott', 'Rosca Neutra Unilateral Scott', 'biceps', 'halteres', 'intermediario', 'bíceps', ARRAY[]::TEXT[], 'Biceps/rosca neutra  unilateral no banco scort.gif', 'Rosca neutra unilateral no scott.'),
    ('rosca_scott_w', 'Rosca Scott Barra W', 'biceps', 'barra', 'intermediario', 'bíceps', ARRAY[]::TEXT[], 'Biceps/rosca no banco scort barra W.gif', 'Rosca scott com barra W.'),
    ('rosca_cabo2', 'Rosca no Cabo', 'biceps', 'cabo', 'iniciante', 'bíceps', ARRAY[]::TEXT[], 'Biceps/Rosca no Cabo.gif', 'Rosca direta no cabo.'),
    ('rosca_scott3', 'Rosca no Scott', 'biceps', 'barra', 'intermediario', 'bíceps', ARRAY[]::TEXT[], 'Biceps/rosca no scort.gif', 'Rosca no banco scott.'),
    ('rosca_pronada_incl', 'Rosca Pronada Banco Inclinado', 'biceps', 'halteres', 'intermediario', 'bíceps', ARRAY['antebraço'], 'Biceps/Rosca pronada no banco inclinado.gif', 'Rosca pronada no banco inclinado.'),
    ('rosca_scott_alt', 'Rosca Scott Alternados', 'biceps', 'halteres', 'intermediario', 'bíceps', ARRAY[]::TEXT[], 'Biceps/Rosca scott alternados com halteres.gif', 'Rosca scott alternada.'),
    ('rosca_scott_alavanca', 'Rosca Scott com Alavanca', 'biceps', 'maquina', 'intermediario', 'bíceps', ARRAY[]::TEXT[], 'Biceps/Rosca Scott com Alavanca.gif', 'Rosca scott na máquina alavanca.'),
    ('rosca_scott_w2', 'Rosca Scott Barra W', 'biceps', 'barra', 'intermediario', 'bíceps', ARRAY[]::TEXT[], 'Biceps/Rosca Scott com Barra W.gif', 'Rosca scott com barra W.'),
    ('rosca_scott_halt', 'Rosca Scott com Halteres', 'biceps', 'halteres', 'intermediario', 'bíceps', ARRAY[]::TEXT[], 'Biceps/Rosca scott com halteres.gif', 'Rosca scott com halteres.'),
    ('rosca_scott_martelo', 'Rosca Scott Halteres Martelo', 'biceps', 'halteres', 'intermediario', 'bíceps', ARRAY[]::TEXT[], 'Biceps/Rosca Scott com Halteres Martelo no Banco.gif', 'Rosca scott martelo.'),
    ('rosca_scott_uni', 'Rosca Scott Unilateral', 'biceps', 'halteres', 'intermediario', 'bíceps', ARRAY[]::TEXT[], 'Biceps/Rosca scott unilateral com halteres.gif', 'Rosca scott unilateral.'),
    ('rosca_scott_uni2', 'Rosca Scott Unilateral 2', 'biceps', 'halteres', 'intermediario', 'bíceps', ARRAY[]::TEXT[], 'Biceps/Rosca Scott Unil com Halteres.gif', 'Rosca scott unilateral variação.'),
    ('rosca_spider_uni', 'Rosca Spider Unilateral', 'biceps', 'halteres', 'avancado', 'bíceps', ARRAY[]::TEXT[], 'Biceps/Rosca spider unilateral.gif', 'Rosca spider unilateral.'),
    ('rosca_uni_cabo', 'Rosca Unilateral com Cabo', 'biceps', 'cabo', 'intermediario', 'bíceps', ARRAY[]::TEXT[], 'Biceps/Rosca Unilateral com Cabo.gif', 'Rosca unilateral no cabo.'),
    ('rosca_uni_halt', 'Rosca Unilateral com Halteres', 'biceps', 'halteres', 'iniciante', 'bíceps', ARRAY[]::TEXT[], 'Biceps/rosca unilateral com halteres.gif', 'Rosca unilateral em pé.'),
    ('rosca_uni_sent', 'Rosca Unilateral Sentado', 'biceps', 'halteres', 'iniciante', 'bíceps', ARRAY[]::TEXT[], 'Biceps/rosca unilateral com halteres sentado no banco.gif', 'Rosca unilateral sentado.'),
    ('rosca_uni_neutra', 'Rosca Unilateral Neutra', 'biceps', 'halteres', 'iniciante', 'bíceps', ARRAY[]::TEXT[], 'Biceps/rosca unilateral pegada neutra com halteres.gif', 'Rosca unilateral pegada neutra.'),
    ('rosca_zottman', 'Rosca Zottman', 'biceps', 'halteres', 'avancado', 'bíceps', ARRAY['antebraço'], 'Biceps/Rosca Zottman.gif', 'Rosca Zottman com rotação.')
ON CONFLICT (id) DO UPDATE SET 
    name = EXCLUDED.name,
    gif_path = EXCLUDED.gif_path,
    description = EXCLUDED.description,
    updated_at = NOW();

-- Verificar total de exercícios de bíceps
SELECT COUNT(*) as total_biceps FROM app_correcrat.exercises WHERE muscle_group_id = 'biceps';
