-- Exercícios de Peitoral COMPLETOS baseados nos GIFs do Supabase Storage
-- Total: 93 exercícios

INSERT INTO app_correcrat.exercises (id, name, muscle_group_id, equipment, difficulty, primary_muscle, secondary_muscles, gif_path, description) VALUES
    ('peitoral_1', 'Peitoral Exercício 1', 'peitoral', 'corpo', 'iniciante', 'peitoral', ARRAY[]::TEXT[], 'peitoral/1.gif', 'Exercício peitoral.'),
    ('apoio_medball', 'Apoio de Frente com Medball', 'peitoral', 'medball', 'intermediario', 'peitoral', ARRAY['tríceps'], 'peitoral/Apoio de frente com medball.gif', 'Flexão com medball.'),
    ('apoio_step', 'Apoio de Frente com Step', 'peitoral', 'corpo', 'intermediario', 'peitoral', ARRAY['tríceps'], 'peitoral/Apoio de frente com step.gif', 'Flexão com step.'),
    ('apoio_joelhos', 'Apoio de Frente de Joelhos', 'peitoral', 'corpo', 'iniciante', 'peitoral', ARRAY['tríceps'], 'peitoral/Apoio de frente de joelhos.gif', 'Flexão nos joelhos.'),
    ('crossover_sup_cabo', 'Crossover Peitoral Superior Cabo', 'peitoral', 'cabo', 'intermediario', 'peitoral', ARRAY['ombros'], 'peitoral/Crossover de peitoral superior com cabo.gif', 'Cross over peitoral superior.'),
    ('crossover_alavanca', 'Crossover na Alavanca', 'peitoral', 'maquina', 'intermediario', 'peitoral', ARRAY['ombros'], 'peitoral/Crossover na Alavanca.gif', 'Crossover alavanca.'),
    ('cross_polia_alta', 'Cross Over Polia Alta', 'peitoral', 'cabo', 'intermediario', 'peitoral', ARRAY['ombros'], 'peitoral/Cross over polia Alta.gif', 'Cross over polia alta.'),
    ('cross_polia_baixa', 'Cross Over Polia Baixa', 'peitoral', 'cabo', 'intermediario', 'peitoral', ARRAY['ombros'], 'peitoral/Cross over polia baixa.gif', 'Cross over polia baixa.'),
    ('cross_polia_media', 'Cross Over Polia Média', 'peitoral', 'cabo', 'intermediario', 'peitoral', ARRAY['ombros'], 'peitoral/Cross over polia media.gif', 'Cross over polia média.'),
    ('crossover_uni_cabo', 'Crossover Unilateral com Cabo', 'peitoral', 'cabo', 'intermediario', 'peitoral', ARRAY['ombros'], 'peitoral/Crossover Unilateral com Cabo.gif', 'Crossover unilateral.'),
    ('crucifixo_baixo_pe', 'Crucifixo Baixo no Cross em Pé', 'peitoral', 'cabo', 'intermediario', 'peitoral', ARRAY['ombros'], 'peitoral/crucifixo beixo no croos em pe.gif', 'Crucifixo baixo em pé.'),
    ('crucifixo_cabo_decl', 'Crucifixo com Cabo Declinado', 'peitoral', 'cabo', 'intermediario', 'peitoral', ARRAY['ombros'], 'peitoral/Crucifixo com Cabo Declinado.gif', 'Crucifixo cabo declinado.'),
    ('crucifixo_halt_decl', 'Crucifixo com Halteres Declinado', 'peitoral', 'halteres', 'intermediario', 'peitoral', ARRAY['ombros'], 'peitoral/Crucifixo com Halteres Declinado.gif', 'Crucifixo halteres declinado.'),
    ('crucifixo_halteres', 'Crucifixo com Halteres', 'peitoral', 'halteres', 'intermediario', 'peitoral', ARRAY['ombros'], 'peitoral/Crucifixo com halteres.gif', 'Crucifixo halteres.'),
    ('crucifixo_halt_incl', 'Crucifixo com Halteres Inclinado', 'peitoral', 'halteres', 'intermediario', 'peitoral', ARRAY['ombros'], 'peitoral/Crucifixo com Halteres Inclinado.gif', 'Crucifixo halteres inclinado.'),
    ('crucifixo_deit_cabo', 'Crucifixo Deitado com Cabo', 'peitoral', 'cabo', 'intermediario', 'peitoral', ARRAY['ombros'], 'peitoral/Crucifixo Deitado com Cabo.gif', 'Crucifixo deitado cabo.'),
    ('crucifixo_incl_banco', 'Crucifixo Inclinado Banco Halteres', 'peitoral', 'halteres', 'intermediario', 'peitoral', ARRAY['ombros'], 'peitoral/crucifixo inclinado banco com halteres.gif', 'Crucifixo inclinado banco.'),
    ('crucifixo_incl_cross', 'Crucifixo Inclinado Cross', 'peitoral', 'cabo', 'intermediario', 'peitoral', ARRAY['ombros'], 'peitoral/Crucifixo Inclinado Cross.gif', 'Crucifixo inclinado cross.'),
    ('crucifixo_maquina', 'Crucifixo Máquina', 'peitoral', 'maquina', 'iniciante', 'peitoral', ARRAY['ombros'], 'peitoral/Crucifixo Maquina.gif', 'Crucifixo máquina.'),
    ('crucifixo_cross_reto', 'Crucifixo no Cross Banco Reto', 'peitoral', 'cabo', 'intermediario', 'peitoral', ARRAY['ombros'], 'peitoral/crucifixo no cross banco reto.gif', 'Crucifixo cross banco reto.'),
    ('crucifixo_cross_alta', 'Crucifixo no Cross Polia Alta', 'peitoral', 'cabo', 'intermediario', 'peitoral', ARRAY['ombros'], 'peitoral/crucifixo no cross polia alta.gif', 'Crucifixo cross polia alta.'),
    ('crucifixo_uni_decl', 'Crucifixo Unilateral Declinado Cabo', 'peitoral', 'cabo', 'intermediario', 'peitoral', ARRAY['ombros'], 'peitoral/Crucifixo Unilateral em Declinado com Cabo.gif', 'Crucifixo unilateral declinado.'),
    ('dumbbell_covers', 'Dumbbell Covers com Halteres', 'peitoral', 'halteres', 'intermediario', 'peitoral', ARRAY['ombros'], 'peitoral/Dumbbell covers com halteres.gif', 'Dumbbell covers.'),
    ('flex_bracos_aberto', 'Flexão de Cotovelo Braços Abertos', 'peitoral', 'corpo', 'intermediario', 'peitoral', ARRAY['tríceps'], 'peitoral/flex de cotovelo bracos aberto.gif', 'Flexão braços abertos.'),
    ('flex_completa', 'Flexão de Cotovelo Completa', 'peitoral', 'corpo', 'intermediario', 'peitoral', ARRAY['tríceps'], 'peitoral/flex de cotovelo completa.gif', 'Flexão completa.'),
    ('flex_declinado', 'Flexão de Cotovelo Declinado', 'peitoral', 'corpo', 'intermediario', 'peitoral', ARRAY['tríceps'], 'peitoral/flex de cotovelo declinado.gif', 'Flexão declinada.'),
    ('flex_decl_banco', 'Flexão de Cotovelo Declinado Banco', 'peitoral', 'corpo', 'intermediario', 'peitoral', ARRAY['tríceps'], 'peitoral/flex de cotovelo declinado utilizando o banco.gif', 'Flexão declinada banco.'),
    ('mergulho_assistido', 'Mergulho de Peito Assistido', 'peitoral', 'maquina', 'iniciante', 'peitoral', ARRAY['tríceps'], 'peitoral/Mergulho de peito assistido.gif', 'Mergulho assistido.'),
    ('paralelas', 'Paralelas', 'peitoral', 'corpo', 'avancado', 'peitoral', ARRAY['tríceps'], 'peitoral/Paralelas.gif', 'Paralelas.'),
    ('peito_paralela', 'Peito na Paralela', 'peitoral', 'corpo', 'avancado', 'peitoral', ARRAY['tríceps'], 'peitoral/peito na paralela.gif', 'Peito na paralela.'),
    ('pullover_haltere', 'Pullover com Haltere', 'peitoral', 'halteres', 'intermediario', 'peitoral', ARRAY['costas'], 'peitoral/Pullover com haltere.gif', 'Pullover haltere.'),
    ('supino_reto_barra', 'Supino Reto com Barra', 'peitoral', 'barra', 'intermediario', 'peitoral', ARRAY['tríceps'], 'peitoral/supindo reto barra.gif', 'Supino reto barra.'),
    ('supino_alt_halt', 'Supino Alternado com Halteres', 'peitoral', 'halteres', 'intermediario', 'peitoral', ARRAY['tríceps'], 'peitoral/Supino Alternado com Halteres.gif', 'Supino alternado.'),
    ('supino_art_maq', 'Supino Articulado Máquina', 'peitoral', 'maquina', 'iniciante', 'peitoral', ARRAY['tríceps'], 'peitoral/supino articulado maquina.gif', 'Supino articulado.'),
    ('supino_alavanca', 'Supino com Alavanca', 'peitoral', 'maquina', 'iniciante', 'peitoral', ARRAY['tríceps'], 'peitoral/Supino com Alavanca.gif', 'Supino alavanca.'),
    ('supino_incl_smith', 'Supino com Banco Inclinado Smith', 'peitoral', 'smith', 'intermediario', 'peitoral', ARRAY['tríceps'], 'peitoral/Supino com banco inclinado no Smith.gif', 'Supino inclinado smith.'),
    ('supino_barra_decl', 'Supino com Barra Declinado', 'peitoral', 'barra', 'intermediario', 'peitoral', ARRAY['tríceps'], 'peitoral/Supino com barra declinado.gif', 'Supino barra declinado.'),
    ('supino_barra_chao', 'Supino com Barra no Chão', 'peitoral', 'barra', 'intermediario', 'peitoral', ARRAY['tríceps'], 'peitoral/Supino com barra no chao.gif', 'Supino barra chão.'),
    ('supino_cabo_sent', 'Supino com Cabo Sentado', 'peitoral', 'cabo', 'intermediario', 'peitoral', ARRAY['tríceps'], 'peitoral/Supino com cabo sentado.gif', 'Supino cabo sentado.'),
    ('supino_halt_fechada', 'Supino com Haltere Pegada Fechada', 'peitoral', 'halteres', 'intermediario', 'peitoral', ARRAY['tríceps'], 'peitoral/Supino com haltere pegada fechada.gif', 'Supino haltere fechada.'),
    ('supino_halt_fechada2', 'Supino com Halteres Pegada Fechada', 'peitoral', 'halteres', 'intermediario', 'peitoral', ARRAY['tríceps'], 'peitoral/Supino com halteres com pegada fechada.gif', 'Supino halteres fechada.'),
    ('supino_halteres', 'Supino com Halteres', 'peitoral', 'halteres', 'intermediario', 'peitoral', ARRAY['tríceps'], 'peitoral/Supino com Halteres.gif', 'Supino halteres.'),
    ('supino_halt_inv', 'Supino com Halteres Pegada Invertida', 'peitoral', 'halteres', 'intermediario', 'peitoral', ARRAY['tríceps'], 'peitoral/Supino com Halteres Pegada Invertida.gif', 'Supino halteres invertida.'),
    ('supino_kettle_uni', 'Supino com Kettlebell Um Braço', 'peitoral', 'kettlebell', 'avancado', 'peitoral', ARRAY['tríceps'], 'peitoral/Supino com kettlebell de um braco.gif', 'Supino kettlebell unilateral.'),
    ('supino_kettle_chao', 'Supino com Kettlebell no Chão', 'peitoral', 'kettlebell', 'intermediario', 'peitoral', ARRAY['tríceps'], 'peitoral/Supino com kettlebell no chao.gif', 'Supino kettlebell chão.'),
    ('supino_peg_aberta', 'Supino com Pegada Aberta', 'peitoral', 'barra', 'intermediario', 'peitoral', ARRAY['tríceps'], 'peitoral/Supino com pegada aberta.gif', 'Supino pegada aberta.'),
    ('supino_peg_fechada', 'Supino com Pegada Fechada', 'peitoral', 'barra', 'intermediario', 'peitoral', ARRAY['tríceps'], 'peitoral/Supino com pegada fechada.gif', 'Supino pegada fechada.'),
    ('supino_fech_cabo', 'Supino com Pegada Fechada Sentado Cabo', 'peitoral', 'cabo', 'intermediario', 'peitoral', ARRAY['tríceps'], 'peitoral/Supino com Pegada Fechada Sentado com Cabo.gif', 'Supino fechada cabo sentado.'),
    ('supino_cruc_halt', 'Supino Crucifixo com Halteres', 'peitoral', 'halteres', 'intermediario', 'peitoral', ARRAY['ombros'], 'peitoral/supino crucifixo com halteres.gif', 'Supino crucifixo halteres.'),
    ('supino_decl_alav', 'Supino Declinado com Alavanca', 'peitoral', 'maquina', 'intermediario', 'peitoral', ARRAY['tríceps'], 'peitoral/Supino declinada com alavanca.gif', 'Supino declinado alavanca.'),
    ('supino_decl_barra', 'Supino Declinado Barra', 'peitoral', 'barra', 'intermediario', 'peitoral', ARRAY['tríceps'], 'peitoral/supino declinado barra.gif', 'Supino declinado barra.'),
    ('supino_decl_aberta', 'Supino Declinado Barra Pegada Aberta', 'peitoral', 'barra', 'intermediario', 'peitoral', ARRAY['tríceps'], 'peitoral/supino declinado barrapegada aberta.gif', 'Supino declinado pegada aberta.'),
    ('supino_decl_halt1', 'Supino Declinado com Halteres 1', 'peitoral', 'halteres', 'intermediario', 'peitoral', ARRAY['tríceps'], 'peitoral/Supino Declinado com Halteres(1).gif', 'Supino declinado halteres.'),
    ('supino_decl_halt2', 'Supino Declinado com Halteres', 'peitoral', 'halteres', 'intermediario', 'peitoral', ARRAY['tríceps'], 'peitoral/supino declinado com halteres.gif', 'Supino declinado halteres.'),
    ('supino_decl_smith', 'Supino Declinado na Máquina Smith', 'peitoral', 'smith', 'intermediario', 'peitoral', ARRAY['tríceps'], 'peitoral/Supino declinado na maquina Smith.gif', 'Supino declinado smith.'),
    ('supino_decl_smit2', 'Supino Declinado no Smith', 'peitoral', 'smith', 'intermediario', 'peitoral', ARRAY['tríceps'], 'peitoral/supino declinado no smit.gif', 'Supino declinado smith.'),
    ('supino_decl_martelo', 'Supino Declinado Pegada Martelo', 'peitoral', 'halteres', 'intermediario', 'peitoral', ARRAY['tríceps'], 'peitoral/Supino declinado pegada martelo.gif', 'Supino declinado martelo.'),
    ('supino_decl_uni_mart', 'Supino Declinado Unilateral Martelo', 'peitoral', 'halteres', 'avancado', 'peitoral', ARRAY['tríceps'], 'peitoral/Supino Declinado Unilateral Pegada Martelo com Haltere.gif', 'Supino declinado unilateral martelo.'),
    ('supino_base', 'Supino', 'peitoral', 'barra', 'intermediario', 'peitoral', ARRAY['tríceps'], 'peitoral/Supino.gif', 'Supino base.'),
    ('supino_horiz_maq', 'Supino Horizontal Máquina', 'peitoral', 'maquina', 'iniciante', 'peitoral', ARRAY['tríceps'], 'peitoral/supino horizontal maquina.gif', 'Supino horizontal máquina.'),
    ('supino_incl_maq', 'Supino Inclinado Máquina', 'peitoral', 'maquina', 'iniciante', 'peitoral', ARRAY['tríceps'], 'peitoral/Supino Incliado Maquina.gif', 'Supino inclinado máquina.'),
    ('supino_incl_art', 'Supino Inclinado Aparelho Articulado', 'peitoral', 'maquina', 'iniciante', 'peitoral', ARRAY['tríceps'], 'peitoral/supino inclinado  aparelho articulado.gif', 'Supino inclinado articulado.'),
    ('supino_incl_cross', 'Supino Inclinado Banco Cross', 'peitoral', 'cabo', 'intermediario', 'peitoral', ARRAY['tríceps'], 'peitoral/supino inclinado banco cross.gif', 'Supino inclinado banco cross.'),
    ('supino_incl_banco', 'Supino Inclinado Banco', 'peitoral', 'barra', 'intermediario', 'peitoral', ARRAY['tríceps'], 'peitoral/supino inclinado banco.gif', 'Supino inclinado banco.'),
    ('supino_incl_smith2', 'Supino Inclinado Banco no Smith', 'peitoral', 'smith', 'intermediario', 'peitoral', ARRAY['tríceps'], 'peitoral/supino inclinado banco no smith.gif', 'Supino inclinado smith.'),
    ('supino_incl_barra', 'Supino Inclinado com Barra', 'peitoral', 'barra', 'intermediario', 'peitoral', ARRAY['tríceps'], 'peitoral/Supino inclinado com barra.gif', 'Supino inclinado barra.'),
    ('supino_incl_cabo', 'Supino Inclinado com Cabo', 'peitoral', 'cabo', 'intermediario', 'peitoral', ARRAY['tríceps'], 'peitoral/Supino inclinado com cabo.gif', 'Supino inclinado cabo.'),
    ('supino_incl_martelo', 'Supino Inclinado Halteres Martelo', 'peitoral', 'halteres', 'intermediario', 'peitoral', ARRAY['tríceps'], 'peitoral/Supino Inclinado com Halteres em Martelo.gif', 'Supino inclinado martelo.'),
    ('supino_incl_fechada', 'Supino Inclinado Halteres Pegada Fechada', 'peitoral', 'halteres', 'intermediario', 'peitoral', ARRAY['tríceps'], 'peitoral/Supino inclinado com halteres e pegada fechada.gif', 'Supino inclinado fechada.'),
    ('supino_incl_inv', 'Supino Inclinado Halteres Pegada Invertida', 'peitoral', 'halteres', 'intermediario', 'peitoral', ARRAY['tríceps'], 'peitoral/Supino Inclinado com Halteres e Pegada Invertida.gif', 'Supino inclinado invertida.'),
    ('supino_incl_halt', 'Supino Inclinado com Halteres', 'peitoral', 'halteres', 'intermediario', 'peitoral', ARRAY['tríceps'], 'peitoral/Supino inclinado com halteres.gif', 'Supino inclinado halteres.'),
    ('supino_incl_halt_um', 'Supino Inclinado com Halteres Um', 'peitoral', 'halteres', 'intermediario', 'peitoral', ARRAY['tríceps'], 'peitoral/Supino Inclinado com Halteres um.gif', 'Supino inclinado halteres.'),
    ('supino_incl_fech', 'Supino Inclinado com Pegada Fechada', 'peitoral', 'barra', 'intermediario', 'peitoral', ARRAY['tríceps'], 'peitoral/Supino inclinado com pegada fechada.gif', 'Supino inclinado pegada fechada.'),
    ('supino_incl_alav', 'Supino Inclinado na Alavanca', 'peitoral', 'maquina', 'iniciante', 'peitoral', ARRAY['tríceps'], 'peitoral/Supino Inclinado na Alavanca.gif', 'Supino inclinado alavanca.'),
    ('supino_incl_smith3', 'Supino Inclinado no Smith', 'peitoral', 'smith', 'intermediario', 'peitoral', ARRAY['tríceps'], 'peitoral/supino inclinado no smith.gif', 'Supino inclinado smith.'),
    ('supino_inv_aberta', 'Supino Invertido com Pegada Aberta', 'peitoral', 'barra', 'intermediario', 'peitoral', ARRAY['tríceps'], 'peitoral/Supino invertido com pegada aberta.gif', 'Supino invertido pegada aberta.'),
    ('supino_30_inv', 'Supino Banco Inclinado 30 Graus Invertida', 'peitoral', 'halteres', 'intermediario', 'peitoral', ARRAY['tríceps'], 'peitoral/Supino no banco inclinado 30 graus com pegada invertida.gif', 'Supino 30 graus invertida.'),
    ('supino_smith_triang', 'Supino no Smith com Triângulo', 'peitoral', 'smith', 'intermediario', 'peitoral', ARRAY['tríceps'], 'peitoral/Supino no smith com o triangulo.gif', 'Supino smith triângulo.'),
    ('supino_peg_martelo', 'Supino Pegada Martelo', 'peitoral', 'halteres', 'intermediario', 'peitoral', ARRAY['tríceps'], 'peitoral/Supino pegada martelo.gif', 'Supino pegada martelo.'),
    ('supino_reto_halt2', 'Supino Reto com Halteres Dois', 'peitoral', 'halteres', 'intermediario', 'peitoral', ARRAY['tríceps'], 'peitoral/Supino reto com halteres dois.gif', 'Supino reto halteres.'),
    ('supino_reto_halt', 'Supino Reto com Halteres', 'peitoral', 'halteres', 'intermediario', 'peitoral', ARRAY['tríceps'], 'peitoral/supino reto com halteres.gif', 'Supino reto halteres.'),
    ('supino_reto_cross', 'Supino Reto em Pé no Cross Over', 'peitoral', 'cabo', 'intermediario', 'peitoral', ARRAY['tríceps'], 'peitoral/Supino reto em pe no cross over.gif', 'Supino reto cross over.'),
    ('supino_reto_maq', 'Supino Reto na Máquina', 'peitoral', 'maquina', 'iniciante', 'peitoral', ARRAY['tríceps'], 'peitoral/Supino Reto na Maquina.gif', 'Supino reto máquina.'),
    ('supino_reto_cross2', 'Supino Reto no Cross', 'peitoral', 'cabo', 'intermediario', 'peitoral', ARRAY['tríceps'], 'peitoral/supino reto  no cross.gif', 'Supino reto cross.'),
    ('supino_reto_aberta', 'Supino Reto Pegada Aberta', 'peitoral', 'barra', 'intermediario', 'peitoral', ARRAY['tríceps'], 'peitoral/supino reto pegada aberta.gif', 'Supino reto pegada aberta.'),
    ('supino_uni_alav', 'Supino Unilateral com Alavanca', 'peitoral', 'maquina', 'intermediario', 'peitoral', ARRAY['tríceps'], 'peitoral/Supino unilateral com Alavanca.gif', 'Supino unilateral alavanca.'),
    ('supino_uni_halt_rev', 'Supino Unilateral Halteres Pegada Reversa', 'peitoral', 'halteres', 'avancado', 'peitoral', ARRAY['tríceps'], 'peitoral/Supino Unilateral com Halteres com Pegada Reversa.gif', 'Supino unilateral reversa.'),
    ('supino_uni_cabo', 'Supino Unilateral no Cabo', 'peitoral', 'cabo', 'intermediario', 'peitoral', ARRAY['tríceps'], 'peitoral/Supino Unilateral no Cabo.gif', 'Supino unilateral cabo.'),
    ('supino_vert_maq', 'Supino Vertical Pegada Neutra Máquina', 'peitoral', 'maquina', 'iniciante', 'peitoral', ARRAY['tríceps'], 'peitoral/supino vertical pegada neutra maquina.gif', 'Supino vertical máquina.'),
    ('voador_halt_cima', 'Voador com Halteres para Cima', 'peitoral', 'halteres', 'intermediario', 'peitoral', ARRAY['ombros'], 'peitoral/Voador com Halteres para Cima.gif', 'Voador halteres para cima.'),
    ('voador_maquina', 'Voador Máquina', 'peitoral', 'maquina', 'iniciante', 'peitoral', ARRAY['ombros'], 'peitoral/voador maquina.gif', 'Voador máquina.'),
    ('voador_pec_deck', 'Voador no Pec Deck', 'peitoral', 'maquina', 'iniciante', 'peitoral', ARRAY['ombros'], 'peitoral/Voador no pec deck.gif', 'Voador pec deck.'),
    ('voador_uni_solo', 'Voador Unilateral no Solo com Barra', 'peitoral', 'barra', 'avancado', 'peitoral', ARRAY['ombros'], 'peitoral/Voador unilateral no Solo com Barra.gif', 'Voador unilateral solo.')
ON CONFLICT (id) DO UPDATE SET 
    name = EXCLUDED.name, 
    gif_path = EXCLUDED.gif_path, 
    equipment = EXCLUDED.equipment,
    difficulty = EXCLUDED.difficulty,
    updated_at = NOW();

-- Verificar total
SELECT COUNT(*) as total_peitoral FROM app_correcrat.exercises WHERE muscle_group_id = 'peitoral';
