-- Exercícios de Ombros baseados nos GIFs do Supabase Storage
INSERT INTO app_correcrat.exercises (id, name, muscle_group_id, equipment, difficulty, primary_muscle, secondary_muscles, gif_path, description) VALUES
    ('cruc_inv_incl', 'Crucifixo Inverso Banco Inclinado', 'ombros', 'halteres', 'intermediario', 'ombros', ARRAY['costas'], 'ombros/crucifixo inverso no banco inclinado.gif', 'Crucifixo inverso no banco inclinado.'),
    ('cruc_inv_cross_reto', 'Crucifixo Inverso Cross Banco Reto', 'ombros', 'cabo', 'intermediario', 'ombros', ARRAY['costas'], 'ombros/crucifixo inverso no cross no banco reto .gif', 'Crucifixo inverso cross banco reto.'),
    ('cruc_inv_uni_cabo', 'Crucifixo Inverso Unilateral Cabo', 'ombros', 'cabo', 'intermediario', 'ombros', ARRAY['costas'], 'ombros/Crucifixo inverso unilateral com cabo.gif', 'Crucifixo inverso unilateral.'),
    ('cruc_inv_halt2', 'Crucifixo Invertido Halteres', 'ombros', 'halteres', 'intermediario', 'ombros', ARRAY['costas'], 'ombros/Crucifixo Invertido com Halteres.gif', 'Crucifixo invertido halteres.'),
    ('cruc_inv_polia', 'Crucifixo Invertido Polia Alta', 'ombros', 'cabo', 'intermediario', 'ombros', ARRAY['costas'], 'ombros/Crucifixo I_nvertido Polia Alta.gif', 'Crucifixo invertido polia alta.'),
    ('desenv_halt', 'Desenvolvimento com Halteres', 'ombros', 'halteres', 'intermediario', 'ombros', ARRAY['tríceps'], 'ombros/Desenvolmento com Halteres.gif', 'Desenvolvimento com halteres.'),
    ('desenv_elastico', 'Desenvolvimento Frontal Elástico', 'ombros', 'elastico', 'iniciante', 'ombros', ARRAY['tríceps'], 'ombros/Desenvolmento Frontal com Elastico.gif', 'Desenvolvimento com elástico.'),
    ('desenv_arnold2', 'Desenvolvimento Arnold', 'ombros', 'halteres', 'avancado', 'ombros', ARRAY['tríceps'], 'ombros/Desenvolvimento Arnold.gif', 'Desenvolvimento Arnold clássico.'),
    ('desenv_arnold_met', 'Desenvolvimento Arnold Metade', 'ombros', 'halteres', 'intermediario', 'ombros', ARRAY['tríceps'], 'ombros/Desenvolvimento Arnold (metade).gif', 'Desenvolvimento Arnold parcial.'),
    ('desenv_nuca', 'Desenvolvimento Barra Nuca', 'ombros', 'barra', 'intermediario', 'ombros', ARRAY['tríceps'], 'ombros/desenvolvimento barra atras da nuca.gif', 'Desenvolvimento por trás nuca.'),
    ('desenv_sent_nuca', 'Desenvolvimento Sentado Nuca', 'ombros', 'barra', 'intermediario', 'ombros', ARRAY['tríceps'], 'ombros/desenvolvimento barra sentado atras nuca.gif', 'Desenvolvimento sentado nuca.'),
    ('desenv_cabo_cross', 'Desenvolvimento Cabo Cross', 'ombros', 'cabo', 'intermediario', 'ombros', ARRAY['tríceps'], 'ombros/desenvolvimento cabo cross.gif', 'Desenvolvimento no cross.'),
    ('desenv_barra2', 'Desenvolvimento com Barra', 'ombros', 'barra', 'intermediario', 'ombros', ARRAY['tríceps'], 'ombros/Desenvolvimento com Barra.gif', 'Desenvolvimento com barra.'),
    ('desenv_barra_sent', 'Desenvolvimento Barra Sentado', 'ombros', 'barra', 'intermediario', 'ombros', ARRAY['tríceps'], 'ombros/Desenvolvimento com Barra sentado.gif', 'Desenvolvimento barra sentado.'),
    ('desenv_halt2', 'Desenvolvimento Halteres', 'ombros', 'halteres', 'intermediario', 'ombros', ARRAY['tríceps'], 'ombros/Desenvolvimento com Halteres.gif', 'Desenvolvimento halteres clássico.'),
    ('desenv_cubano', 'Desenvolvimento Cubano', 'ombros', 'halteres', 'avancado', 'ombros', ARRAY['tríceps'], 'ombros/Desenvolvimento Cubano com Halteres.gif', 'Desenvolvimento cubano.'),
    ('desenv_cubano_sent', 'Desenvolvimento Cubano Sentado', 'ombros', 'halteres', 'avancado', 'ombros', ARRAY['tríceps'], 'ombros/Desenvolvimento cubano sentado com halteres.gif', 'Desenvolvimento cubano sentado.'),
    ('desenv_barra_sent2', 'Desenvolvimento Ombro Barra Sentado', 'ombros', 'barra', 'intermediario', 'ombros', ARRAY['tríceps'], 'ombros/Desenvolvimento de ombro com barra sentado.gif', 'Desenvolvimento ombro barra sentado.'),
    ('desenv_cabo_ajoel', 'Desenvolvimento Cabo Ajoelhado', 'ombros', 'cabo', 'intermediario', 'ombros', ARRAY['tríceps'], 'ombros/Desenvolvimento de ombro com cabo ajoelhado.gif', 'Desenvolvimento cabo ajoelhado.'),
    ('desenv_cabo', 'Desenvolvimento Ombro Cabo', 'ombros', 'cabo', 'intermediario', 'ombros', ARRAY['tríceps'], 'ombros/Desenvolvimento de ombro com cabo.gif', 'Desenvolvimento ombro cabo.'),
    ('desenv_w', 'Desenvolvimento Halteres W', 'ombros', 'halteres', 'intermediario', 'ombros', ARRAY['tríceps'], 'ombros/Desenvolvimento de ombro com halteres em forma de W.gif', 'Desenvolvimento em W.'),
    ('desenv_z', 'Desenvolvimento Halteres Z', 'ombros', 'halteres', 'intermediario', 'ombros', ARRAY['tríceps'], 'ombros/Desenvolvimento de ombro com halteres em Z.gif', 'Desenvolvimento em Z.'),
    ('desenv_deitado', 'Desenvolvimento Ombro Deitado', 'ombros', 'halteres', 'intermediario', 'ombros', ARRAY['tríceps'], 'ombros/Desenvolvimento de ombro deitado.gif', 'Desenvolvimento deitado.'),
    ('desenv_banco_halt', 'Desenvolvimento Banco Halteres', 'ombros', 'halteres', 'intermediario', 'ombros', ARRAY['tríceps'], 'ombros/Desenvolvimento de Ombro no Banco com Halteres.gif', 'Desenvolvimento banco halteres.'),
    ('desenv_w_inv', 'Desenvolvimento Barra W Invertida', 'ombros', 'barra', 'intermediario', 'ombros', ARRAY['tríceps'], 'ombros/Desenvolvimento de ombros com barra W com pegada invertida.gif', 'Desenvolvimento barra W invertida.'),
    ('desenv_uni_halt', 'Desenvolvimento Unilateral Halter', 'ombros', 'halteres', 'intermediario', 'ombros', ARRAY['tríceps'], 'ombros/Desenvolvimento de ombro unilateral com halter.gif', 'Desenvolvimento unilateral.'),
    ('desenv_militar', 'Desenvolvimento Militar Barra', 'ombros', 'barra', 'intermediario', 'ombros', ARRAY['tríceps'], 'ombros/Desenvolvimento militar com barra.gif', 'Desenvolvimento militar.'),
    ('desenv_militar_fech', 'Desenvolvimento Militar Fechada', 'ombros', 'barra', 'intermediario', 'ombros', ARRAY['tríceps'], 'ombros/Desenvolvimento militar com pegada fechada.gif', 'Desenvolvimento militar fechada.'),
    ('desenv_barra3', 'Desenvolvimento na Barra', 'ombros', 'barra', 'intermediario', 'ombros', ARRAY['tríceps'], 'ombros/desenvolvimento na barra.gif', 'Desenvolvimento na barra.'),
    ('desenv_smith_nuca', 'Desenvolvimento Smith Nuca', 'ombros', 'smith', 'intermediario', 'ombros', ARRAY['tríceps'], 'ombros/desenvolvimento no smith barra na nuca.gif', 'Desenvolvimento smith nuca.'),
    ('desenv_tras_barra', 'Desenvolvimento Por Trás Barra', 'ombros', 'barra', 'intermediario', 'ombros', ARRAY['tríceps'], 'ombros/Desenvolvimento por tras com barra.gif', 'Desenvolvimento por trás.'),
    ('desenv_sent_halt', 'Desenvolvimento Sentado Halteres', 'ombros', 'halteres', 'intermediario', 'ombros', ARRAY['tríceps'], 'ombros/Desenvolvimento Sentado com Halteres.gif', 'Desenvolvimento sentado halteres.'),
    ('desenv_sent_smith', 'Desenvolvimento Sentado Smith', 'ombros', 'smith', 'iniciante', 'ombros', ARRAY['tríceps'], 'ombros/Desenvolvimento Sentado Smith.gif', 'Desenvolvimento sentado smith.'),
    ('desenv_smith', 'Desenvolvimento Smith', 'ombros', 'smith', 'iniciante', 'ombros', ARRAY['tríceps'], 'ombros/Desenvolvimento Smith.gif', 'Desenvolvimento smith.'),
    ('desenv_uni', 'Desenvolvimento Unilateral', 'ombros', 'halteres', 'intermediario', 'ombros', ARRAY['tríceps'], 'ombros/desenvolvimento unilateral.gif', 'Desenvolvimento unilateral.'),
    ('desenv_frente_sent', 'Desenvolvimento Barra Frente Sentado', 'ombros', 'barra', 'intermediario', 'ombros', ARRAY['tríceps'], 'ombros/desnvolvimento barra frente sentado.gif', 'Desenvolvimento barra frente sentado.'),
    ('elev_bi_maq', 'Elevação Bilateral Máquina', 'ombros', 'maquina', 'iniciante', 'ombros', ARRAY[]::TEXT[], 'ombros/elevacao bilateral na maquina.gif', 'Elevação bilateral máquina.'),
    ('elev_cotovelo_uni', 'Elevação Cotovelo Unilateral', 'ombros', 'halteres', 'intermediario', 'ombros', ARRAY[]::TEXT[], 'ombros/elevacao do cotovelo unilateral.gif', 'Elevação cotovelo unilateral.'),
    ('elev_front_alt', 'Elevação Frontal Alternada', 'ombros', 'halteres', 'iniciante', 'ombros', ARRAY[]::TEXT[], 'ombros/Elevacao Frontal Alternada Com Halteres.gif', 'Elevação frontal alternada.'),
    ('elev_front_barra', 'Elevação Frontal Barra', 'ombros', 'barra', 'iniciante', 'ombros', ARRAY[]::TEXT[], 'ombros/Elevacao Frontal com Barra.gif', 'Elevação frontal barra.'),
    ('elev_front_barra_giro', 'Elevação Frontal Barra Girando', 'ombros', 'barra', 'intermediario', 'ombros', ARRAY[]::TEXT[], 'ombros/Elevacao frontal com barra girando.gif', 'Elevação frontal barra girando.'),
    ('elev_front_w_incl', 'Elevação Frontal Barra W Inclinada', 'ombros', 'barra', 'intermediario', 'ombros', ARRAY[]::TEXT[], 'ombros/Elevacao frontal com barra w inclinada.gif', 'Elevação frontal barra W inclinada.'),
    ('elev_front_cabo_duplo', 'Elevação Frontal Cabo Duplo', 'ombros', 'cabo', 'intermediario', 'ombros', ARRAY[]::TEXT[], 'ombros/elevacao frontal com cabo duplo no cross.gif', 'Elevação frontal cabo duplo.'),
    ('elev_front_halt1', 'Elevação Frontal Halteres 1', 'ombros', 'halteres', 'iniciante', 'ombros', ARRAY[]::TEXT[], 'ombros/Elevacao frontal com halteres 1.gif', 'Elevação frontal halteres.'),
    ('elev_front_halt2', 'Elevação Frontal Halteres', 'ombros', 'halteres', 'iniciante', 'ombros', ARRAY[]::TEXT[], 'ombros/elevacao frontal com halteres.gif', 'Elevação frontal halteres.'),
    ('elev_front_sent', 'Elevação Frontal Sentado', 'ombros', 'halteres', 'iniciante', 'ombros', ARRAY[]::TEXT[], 'ombros/Elevacao frontal com halteres sentado.gif', 'Elevação frontal sentado.'),
    ('elev_front_cross', 'Elevação Frontal Crossover', 'ombros', 'cabo', 'intermediario', 'ombros', ARRAY[]::TEXT[], 'ombros/Elevacao Frontal Crossover.gif', 'Elevação frontal crossover.'),
    ('elev_lat_alt', 'Elevação Lateral Alternada', 'ombros', 'halteres', 'iniciante', 'ombros', ARRAY[]::TEXT[], 'ombros/Elevacao lateral alternada com halteres.gif', 'Elevação lateral alternada.'),
    ('elev_lat_barra_chao', 'Elevação Lateral Barra Chão', 'ombros', 'barra', 'intermediario', 'ombros', ARRAY[]::TEXT[], 'ombros/Elevacao lateral com barra no chao.gif', 'Elevação lateral barra chão.'),
    ('elev_lat_apoio_peito', 'Elevação Lateral Apoio Peito', 'ombros', 'halteres', 'intermediario', 'ombros', ARRAY[]::TEXT[], 'ombros/Elevacao lateral com halteres com apoio no peito.gif', 'Elevação lateral apoio peito.'),
    ('elev_lat_post_deit', 'Elevação Lateral Posterior Deitado', 'ombros', 'halteres', 'intermediario', 'ombros', ARRAY[]::TEXT[], 'ombros/Elevacao lateral com halteres para deltoides posteriores deitado.gif', 'Elevação lateral posterior deitado.'),
    ('elev_lat_sent', 'Elevação Lateral Sentado', 'ombros', 'halteres', 'iniciante', 'ombros', ARRAY[]::TEXT[], 'ombros/Elevacao lateral com halteres sentado.gif', 'Elevação lateral sentado.'),
    ('elev_lat_incl', 'Elevação Lateral Tronco Inclinado', 'ombros', 'halteres', 'intermediario', 'ombros', ARRAY[]::TEXT[], 'ombros/Elevacao lateral com tronco inclinado.gif', 'Elevação lateral inclinado.'),
    ('elev_lat_cruzada', 'Elevação Lateral Cruzada Cross', 'ombros', 'cabo', 'intermediario', 'ombros', ARRAY[]::TEXT[], 'ombros/Elevacao lateral cruzada no crossover.gif', 'Elevação lateral cruzada.'),
    ('elev_lat_cabo2', 'Elevação Lateral Cabo', 'ombros', 'cabo', 'intermediario', 'ombros', ARRAY[]::TEXT[], 'ombros/Elevacao lateral de bracos com cabo.gif', 'Elevação lateral cabo.'),
    ('elev_lat_halt', 'Elevação Lateral Halteres', 'ombros', 'halteres', 'iniciante', 'ombros', ARRAY[]::TEXT[], 'ombros/Elevacao lateral de bracos com halteres.gif', 'Elevação lateral halteres.'),
    ('elev_lat_halt_incl', 'Elevação Lateral Halteres Inclinada', 'ombros', 'halteres', 'intermediario', 'ombros', ARRAY[]::TEXT[], 'ombros/Elevacao lateral de halteres inclinada.gif', 'Elevação lateral inclinada.'),
    ('elev_lat_deit', 'Elevação Lateral Deitado', 'ombros', 'halteres', 'intermediario', 'ombros', ARRAY[]::TEXT[], 'ombros/Elevacao lateral deitado.gif', 'Elevação lateral deitado.'),
    ('elev_lat_front', 'Elevação Lateral e Frontal', 'ombros', 'halteres', 'intermediario', 'ombros', ARRAY[]::TEXT[], 'ombros/Elevacao lateral e frontal com halteres.gif', 'Elevação lateral e frontal.'),
    ('elev_lat_incl_sent', 'Elevação Lateral Inclinado Sentado', 'ombros', 'halteres', 'intermediario', 'ombros', ARRAY[]::TEXT[], 'ombros/elevacao lateral inclinado sentado.gif', 'Elevação lateral inclinado sentado.'),
    ('elev_lat_maq', 'Elevação Lateral Máquina', 'ombros', 'maquina', 'iniciante', 'ombros', ARRAY[]::TEXT[], 'ombros/Elevacao lateral na maquina.gif', 'Elevação lateral máquina.'),
    ('elev_lat_neutra_inv', 'Elevação Lateral Neutra Inversa', 'ombros', 'halteres', 'intermediario', 'ombros', ARRAY[]::TEXT[], 'ombros/elevacao lateral pegada neutra inversa.gif', 'Elevação lateral neutra inversa.'),
    ('elev_lat_sent_banco', 'Elevação Lateral Sentado Banco', 'ombros', 'halteres', 'iniciante', 'ombros', ARRAY[]::TEXT[], 'ombros/elevacao lateral sentado no banco.gif', 'Elevação lateral sentado banco.'),
    ('elev_lat_uni_cabo', 'Elevação Lateral Unilateral Cabo', 'ombros', 'cabo', 'intermediario', 'ombros', ARRAY[]::TEXT[], 'ombros/Elevacao lateral unilateral com cabo.gif', 'Elevação lateral unilateral cabo.'),
    ('elev_lat_uni_incl', 'Elevação Lateral Unilateral Inclinado', 'ombros', 'halteres', 'intermediario', 'ombros', ARRAY[]::TEXT[], 'ombros/Elevacao lateral unilateral com haltere inclinado.gif', 'Elevação lateral unilateral inclinado.'),
    ('elev_lat_uni_halt', 'Elevação Lateral Unilateral Halteres', 'ombros', 'halteres', 'iniciante', 'ombros', ARRAY[]::TEXT[], 'ombros/Elevacao lateral unilateral com halteres.gif', 'Elevação lateral unilateral.'),
    ('elev_lat3', 'Elevação Lateral Halteres', 'ombros', 'halteres', 'iniciante', 'ombros', ARRAY[]::TEXT[], 'ombros/elevacao letaral com haltrers.gif', 'Elevação lateral clássica.'),
    ('elev_lat_cruzada2', 'Elevação Lateral Cruzada Cross', 'ombros', 'cabo', 'intermediario', 'ombros', ARRAY[]::TEXT[], 'ombros/elevacao leteral cruzada no cross.gif', 'Elevação lateral cruzada cross.'),
    ('elev_post_uni_prono', 'Elevação Posterior Unilateral Prono', 'ombros', 'halteres', 'intermediario', 'ombros', ARRAY[]::TEXT[], 'ombros/Elevacao Posterior unilateral com halteres em Decubito Prono.gif', 'Elevação posterior unilateral prono.'),
    ('elev_uni_front', 'Elevação Unilateral Frontal', 'ombros', 'halteres', 'iniciante', 'ombros', ARRAY[]::TEXT[], 'ombros/elevacao unilateral frontal.gif', 'Elevação unilateral frontal.'),
    ('elev_uni', 'Elevação Unilateral', 'ombros', 'halteres', 'iniciante', 'ombros', ARRAY[]::TEXT[], 'ombros/elevacao unilateral.gif', 'Elevação unilateral.'),
    ('elev_uni_cross', 'Elevação Unilateral Cross', 'ombros', 'cabo', 'intermediario', 'ombros', ARRAY[]::TEXT[], 'ombros/elevacao unilateral no cross.gif', 'Elevação unilateral cross.'),
    ('elev_front_apoio', 'Elevações Frontais Apoiadas Peito', 'ombros', 'halteres', 'intermediario', 'ombros', ARRAY[]::TEXT[], 'ombros/Elevacoes frontais com halteres apoiadas no peito.gif', 'Elevações frontais apoiadas.'),
    ('lev_halt_4_formas', 'Levantamento Halteres 4 Formas', 'ombros', 'halteres', 'avancado', 'ombros', ARRAY[]::TEXT[], 'ombros/Levantamento de halteres de quatro maneiras dois.gif', 'Levantamento 4 formas.'),
    ('lev_halt_3_formas', 'Levantamento Halteres 3 Formas', 'ombros', 'halteres', 'avancado', 'ombros', ARRAY[]::TEXT[], 'ombros/Levantamento de halteres de tres maneiras.gif', 'Levantamento 3 formas.'),
    ('lev_front_alt_sent', 'Levantamento Frontal Alternado Sentado', 'ombros', 'halteres', 'iniciante', 'ombros', ARRAY[]::TEXT[], 'ombros/Levantamento frontal alternado com haltere sentado.gif', 'Levantamento frontal alternado sentado.'),
    ('lev_front_anilha', 'Levantamento Frontal Anilha', 'ombros', 'anilha', 'iniciante', 'ombros', ARRAY[]::TEXT[], 'ombros/Levantamento frontal com anilha.gif', 'Levantamento frontal anilha.'),
    ('lev_front_barra', 'Levantamento Frontal Barra', 'ombros', 'barra', 'iniciante', 'ombros', ARRAY[]::TEXT[], 'ombros/Levantamento frontal com barra.gif', 'Levantamento frontal barra.'),
    ('lev_front_uni_cabo', 'Levantamento Frontal Unilateral Cabo', 'ombros', 'cabo', 'intermediario', 'ombros', ARRAY[]::TEXT[], 'ombros/Levantamento frontal unilateral com cabo.gif', 'Levantamento frontal unilateral cabo.'),
    ('post_ombro_polia', 'Posterior Ombro Polia', 'ombros', 'cabo', 'intermediario', 'ombros', ARRAY[]::TEXT[], 'ombros/POSTERIOR DE OMBRO NA POLIA.gif', 'Posterior de ombro polia.'),
    ('remada_alta_cross', 'Remada Alta Barra Cross', 'ombros', 'cabo', 'intermediario', 'ombros', ARRAY['trapézio'], 'ombros/remada alta com barra no cross.gif', 'Remada alta cross.'),
    ('remada_alta_aberta', 'Remada Alta Pegada Aberta', 'ombros', 'barra', 'intermediario', 'ombros', ARRAY['trapézio'], 'ombros/remada alta com barra pegada aberta.gif', 'Remada alta pegada aberta.'),
    ('remada_alta_w', 'Remada Alta Barra W', 'ombros', 'barra', 'intermediario', 'ombros', ARRAY['trapézio'], 'ombros/remada alta com barra W.gif', 'Remada alta barra W.'),
    ('remada_alta_bi_halt', 'Remada Alta Bilateral Halteres', 'ombros', 'halteres', 'intermediario', 'ombros', ARRAY['trapézio'], 'ombros/remada alta com halteres bilateral.gif', 'Remada alta bilateral halteres.'),
    ('remada_alta_halt', 'Remada Alta Halteres', 'ombros', 'halteres', 'intermediario', 'ombros', ARRAY['trapézio'], 'ombros/remada alta com halteres.gif', 'Remada alta halteres.'),
    ('remada_alta_cross2', 'Remada Alta Cross', 'ombros', 'cabo', 'intermediario', 'ombros', ARRAY['trapézio'], 'ombros/remada alta no cross.gif', 'Remada alta cross.'),
    ('remada_alta_um', 'Remada Alta Um', 'ombros', 'barra', 'intermediario', 'ombros', ARRAY['trapézio'], 'ombros/Remada Alta um.gif', 'Remada alta.'),
    ('remada_post_halt', 'Remada Posterior Halteres', 'ombros', 'halteres', 'intermediario', 'ombros', ARRAY[]::TEXT[], 'ombros/Remada com halteres para a posterior de ombros.gif', 'Remada posterior halteres.'),
    ('remada_delt_sent', 'Remada Deltoide Posterior Sentado', 'ombros', 'halteres', 'intermediario', 'ombros', ARRAY[]::TEXT[], 'ombros/Remada de deltoide posterior sentado com haltere.gif', 'Remada deltoide posterior.'),
    ('remada_incl_45', 'Remada Inclinada 45 Graus', 'ombros', 'halteres', 'intermediario', 'ombros', ARRAY[]::TEXT[], 'ombros/Remada inclinada a 45 graus.gif', 'Remada inclinada 45 graus.'),
    ('remada_inv_cabos', 'Remada Inversa Cabos Deitado', 'ombros', 'cabo', 'intermediario', 'ombros', ARRAY[]::TEXT[], 'ombros/Remada inversa com cabos deitado.gif', 'Remada inversa cabos deitado.'),
    ('remada_lat_sent', 'Remada Lateral Sentado', 'ombros', 'halteres', 'intermediario', 'ombros', ARRAY[]::TEXT[], 'ombros/Remada lateral com halteres sentado.gif', 'Remada lateral sentado.'),
    ('remada_livre_barra', 'Remada Livre Barra', 'ombros', 'barra', 'intermediario', 'ombros', ARRAY['trapézio'], 'ombros/remada livre com barra.gif', 'Remada livre barra.'),
    ('remada_alta_barra', 'Remada Alta com Barra', 'ombros', 'barra', 'intermediario', 'ombros', ARRAY['trapézio'], 'ombros/Remanda Alta com Barra.gif', 'Remada alta barra.'),
    ('voador_inv', 'Voador Inverso', 'ombros', 'maquina', 'iniciante', 'ombros', ARRAY['costas'], 'ombros/voador inverso.gif', 'Voador inverso.'),
    ('voador_inv2', 'Voador Invertido', 'ombros', 'maquina', 'iniciante', 'ombros', ARRAY['costas'], 'ombros/Voador invertido.gif', 'Voador invertido.'),
    ('voador_post_cabo', 'Voador Posterior Cabo', 'ombros', 'cabo', 'intermediario', 'ombros', ARRAY['costas'], 'ombros/Voador para deltoides posterior com cabo.gif', 'Voador posterior cabo.')
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, gif_path = EXCLUDED.gif_path, updated_at = NOW();

SELECT COUNT(*) as total_ombros FROM app_correcrat.exercises WHERE muscle_group_id = 'ombros';
