-- Exercícios de Pernas baseados nos GIFs do Supabase Storage
INSERT INTO app_correcrat.exercises (id, name, muscle_group_id, equipment, difficulty, primary_muscle, secondary_muscles, gif_path, description) VALUES
    ('aducao_cabo', 'Adução Quadril com Cabo', 'pernas', 'cabo', 'intermediario', 'pernas', ARRAY['adutores'], 'pernas/Aducao do Quadril com Cabo.gif', 'Adução quadril no cabo.'),
    ('aducao_alavanca', 'Adução Quadril Lateral Alavanca', 'pernas', 'maquina', 'iniciante', 'pernas', ARRAY['adutores'], 'pernas/Aducao do Quadril Lateral com Alavanca.gif', 'Adução quadril alavanca.'),
    ('afundo_barra', 'Afundo com Barra', 'pernas', 'barra', 'intermediario', 'pernas', ARRAY['glúteos'], 'pernas/Afundo com Barra.gif', 'Afundo com barra.'),
    ('afundo_halt2', 'Afundo com Halteres', 'pernas', 'halteres', 'intermediario', 'pernas', ARRAY['glúteos'], 'pernas/Afundo com Halteres.gif', 'Afundo com halteres.'),
    ('afundo_landmine', 'Afundo com Landmine', 'pernas', 'barra', 'intermediario', 'pernas', ARRAY['glúteos'], 'pernas/Afundo com landmine.gif', 'Afundo no landmine.'),
    ('afundo_lateral', 'Afundo Lateral com Barra', 'pernas', 'barra', 'intermediario', 'pernas', ARRAY['glúteos'], 'pernas/Afundo Lateral com Barra.gif', 'Afundo lateral.'),
    ('afundo_banco', 'Afundo no Banco com Halteres', 'pernas', 'halteres', 'intermediario', 'pernas', ARRAY['glúteos'], 'pernas/Afundo no banco com halteres.gif', 'Afundo búlgaro.'),
    ('agach_cinto', 'Agachamento com Cinto', 'pernas', 'maquina', 'intermediario', 'pernas', ARRAY['glúteos'], 'pernas/Agachamento com Cinto.gif', 'Agachamento com cinto.'),
    ('agach_halt_banco', 'Agachamento Halteres Banco', 'pernas', 'halteres', 'intermediario', 'pernas', ARRAY['glúteos'], 'pernas/Agachamento com Halteres no Banco.gif', 'Agachamento halteres banco.'),
    ('agach_kettlebell', 'Agachamento com Kettlebell', 'pernas', 'kettlebell', 'iniciante', 'pernas', ARRAY['glúteos'], 'pernas/Agachamento com kettlebell.gif', 'Agachamento kettlebell.'),
    ('agach_salto_halt', 'Agachamento Salto Halteres', 'pernas', 'halteres', 'avancado', 'pernas', ARRAY['glúteos'], 'pernas/Agachamento com salto e halteres.gif', 'Agachamento salto halteres.'),
    ('agach_salto_hex', 'Agachamento Salto Barra Hexagonal', 'pernas', 'barra', 'avancado', 'pernas', ARRAY['glúteos'], 'pernas/Agachamento com Salto usando Barra Hexagonal.gif', 'Agachamento salto barra hex.'),
    ('agach_trava', 'Agachamento com Trava', 'pernas', 'maquina', 'intermediario', 'pernas', ARRAY['glúteos'], 'pernas/Agachamento com Trava.gif', 'Agachamento com trava.'),
    ('agach_front_banco', 'Agachamento Frontal Barra Banco', 'pernas', 'barra', 'intermediario', 'pernas', ARRAY['core'], 'pernas/Agachamento Frontal com Barra no Banco.gif', 'Agachamento frontal banco.'),
    ('agach_front_smith', 'Agachamento Frontal Smith', 'pernas', 'smith', 'intermediario', 'pernas', ARRAY['core'], 'pernas/Agachamento Frontal com Barra no Smith.gif', 'Agachamento frontal smith.'),
    ('agach_front_cabo', 'Agachamento Frontal Cabo', 'pernas', 'cabo', 'intermediario', 'pernas', ARRAY['core'], 'pernas/Agachamento Frontal com Cabo.gif', 'Agachamento frontal cabo.'),
    ('agach_front_halt', 'Agachamento Frontal Haltere', 'pernas', 'halteres', 'intermediario', 'pernas', ARRAY['core'], 'pernas/Agachamento Frontal com haltere.gif', 'Agachamento frontal haltere.'),
    ('agach_front_kettle', 'Agachamento Frontal Kettlebell', 'pernas', 'kettlebell', 'intermediario', 'pernas', ARRAY['core'], 'pernas/Agachamento Frontal com Kettlebell.gif', 'Agachamento frontal kettlebell.'),
    ('agach_frontal', 'Agachamento Frontal', 'pernas', 'barra', 'avancado', 'pernas', ARRAY['core'], 'pernas/Agachamento Frontal.gif', 'Agachamento frontal clássico.'),
    ('agach2', 'Agachamento', 'pernas', 'barra', 'intermediario', 'pernas', ARRAY['glúteos', 'lombar'], 'pernas/Agachamento.gif', 'Agachamento clássico.'),
    ('agach_goblet', 'Agachamento Goblet Haltere', 'pernas', 'halteres', 'iniciante', 'pernas', ARRAY['core'], 'pernas/Agachamento Goblet com Haltere.gif', 'Agachamento goblet.'),
    ('agach_hack_barra', 'Agachamento Hack Barra', 'pernas', 'barra', 'avancado', 'pernas', ARRAY['glúteos'], 'pernas/Agachamento hack com barra.gif', 'Agachamento hack barra.'),
    ('agach_hack_inv', 'Agachamento Hack Invertido', 'pernas', 'maquina', 'intermediario', 'pernas', ARRAY['glúteos'], 'pernas/Agachamento Hack Invertido.gif', 'Agachamento hack invertido.'),
    ('agach_jefferson', 'Agachamento Jefferson', 'pernas', 'barra', 'avancado', 'pernas', ARRAY['glúteos'], 'pernas/Agachamento Jefferson.gif', 'Agachamento jefferson.'),
    ('agach_landmine', 'Agachamento no Landmine', 'pernas', 'barra', 'intermediario', 'pernas', ARRAY['glúteos'], 'pernas/Agachamento no Landmine.gif', 'Agachamento landmine.'),
    ('agach_smith2', 'Agachamento no Smith', 'pernas', 'smith', 'iniciante', 'pernas', ARRAY['glúteos'], 'pernas/Agachamento no Smith.gif', 'Agachamento smith.'),
    ('agach_sissy', 'Agachamento Sissy', 'pernas', 'corpo', 'avancado', 'pernas', ARRAY[]::TEXT[], 'pernas/Agachamento Sissy.gif', 'Agachamento sissy.'),
    ('agach_skater', 'Agachamento Skater', 'pernas', 'corpo', 'intermediario', 'pernas', ARRAY['glúteos'], 'pernas/Agachamento Skater.gif', 'Agachamento skater.'),
    ('agach_sumo_barra', 'Agachamento Sumô Barra', 'pernas', 'barra', 'intermediario', 'pernas', ARRAY['glúteos', 'adutores'], 'pernas/Agachamento Sumo com Barra.gif', 'Agachamento sumô barra.'),
    ('agach_sumo_halt', 'Agachamento Sumô Halteres', 'pernas', 'halteres', 'intermediario', 'pernas', ARRAY['glúteos', 'adutores'], 'pernas/Agachamento Sumo com Halteres.gif', 'Agachamento sumô halteres.'),
    ('agach_sumo_sp', 'Agachamento Sumô Sem Peso', 'pernas', 'corpo', 'iniciante', 'pernas', ARRAY['glúteos', 'adutores'], 'pernas/Agachamento Sumo sem Pesos.gif', 'Agachamento sumô sem peso.'),
    ('agach_uni_cruz', 'Agachamento Unilateral Cruzado', 'pernas', 'barra', 'avancado', 'pernas', ARRAY['glúteos'], 'pernas/Agachamento unilateral cruzado com Barra.gif', 'Agachamento unilateral cruzado.'),
    ('agach_zercher', 'Agachamento Zercher', 'pernas', 'barra', 'avancado', 'pernas', ARRAY['core'], 'pernas/Agachamento Zercher.gif', 'Agachamento zercher.'),
    ('avanco_barra', 'Avanço com Barra', 'pernas', 'barra', 'intermediario', 'pernas', ARRAY['glúteos'], 'pernas/Avanco com Barra.gif', 'Avanço com barra.'),
    ('avanco_cabo', 'Avanço com Cabo', 'pernas', 'cabo', 'intermediario', 'pernas', ARRAY['glúteos'], 'pernas/Avanco com Cabo.gif', 'Avanço com cabo.'),
    ('avanco_halt', 'Avanço com Halteres', 'pernas', 'halteres', 'intermediario', 'pernas', ARRAY['glúteos'], 'pernas/Avanco com Halteres.gif', 'Avanço com halteres.'),
    ('avanco_puxador', 'Avanço com Puxador Cabo', 'pernas', 'cabo', 'intermediario', 'pernas', ARRAY['glúteos'], 'pernas/Avanco com Puxador de Cabo.gif', 'Avanço puxador cabo.'),
    ('avanco_inv_halt', 'Avanço Invertido Halteres', 'pernas', 'halteres', 'intermediario', 'pernas', ARRAY['glúteos'], 'pernas/Avanco Invertido com Halteres.gif', 'Avanço invertido halteres.'),
    ('avanco_inv', 'Avanço Invertido', 'pernas', 'corpo', 'intermediario', 'pernas', ARRAY['glúteos'], 'pernas/Avanco Invertido.gif', 'Avanço invertido.'),
    ('avanco_sp', 'Avanço Peso Corporal', 'pernas', 'corpo', 'iniciante', 'pernas', ARRAY['glúteos'], 'pernas/Avanco sem Peso Corporal.gif', 'Avanço peso corporal.'),
    ('bom_dia', 'Bom Dia', 'pernas', 'barra', 'intermediario', 'pernas', ARRAY['lombar', 'glúteos'], 'pernas/Bom dia.gif', 'Bom dia.'),
    ('bom_dia2', 'Bom Dia Um', 'pernas', 'barra', 'intermediario', 'pernas', ARRAY['lombar', 'glúteos'], 'pernas/Bom dia um.gif', 'Bom dia variação.'),
    ('cadeira_ext2', 'Cadeira Extensora', 'pernas', 'maquina', 'iniciante', 'pernas', ARRAY[]::TEXT[], 'pernas/Cadeira extensora.gif', 'Cadeira extensora.'),
    ('cadeira_flex2', 'Cadeira Flexora', 'pernas', 'maquina', 'iniciante', 'pernas', ARRAY[]::TEXT[], 'pernas/Cadeira flexora.gif', 'Cadeira flexora.'),
    ('elev_barra_degrau', 'Elevação Barra Degrau', 'pernas', 'barra', 'intermediario', 'pernas', ARRAY['glúteos'], 'pernas/Elevacao com Barra em Degrau.gif', 'Elevação barra degrau.'),
    ('elev_joelho_halt', 'Elevação Joelho Halteres', 'pernas', 'halteres', 'intermediario', 'pernas', ARRAY['glúteos'], 'pernas/Elevacao de Joelho com Halteres.gif', 'Elevação joelho halteres.'),
    ('ext_perna_uni', 'Extensão Perna Unilateral', 'pernas', 'maquina', 'intermediario', 'pernas', ARRAY[]::TEXT[], 'pernas/Extensao de Perna Unilateral.gif', 'Extensão perna unilateral.'),
    ('flex_alavanca', 'Flexão Pernas Alavanca', 'pernas', 'maquina', 'intermediario', 'pernas', ARRAY[]::TEXT[], 'pernas/Flexao de Pernas com Alavanca.gif', 'Flexão pernas alavanca.'),
    ('flex_halt_decl', 'Flexão Pernas Halteres Declinado', 'pernas', 'halteres', 'avancado', 'pernas', ARRAY[]::TEXT[], 'pernas/Flexao de Pernas com Halteres Declinado.gif', 'Flexão pernas halteres.'),
    ('flex_bola', 'Flexão Pernas Bola Estabilidade', 'pernas', 'corpo', 'avancado', 'pernas', ARRAY[]::TEXT[], 'pernas/Flexao de Pernas na Bola de Estabilidade.gif', 'Flexão pernas bola.'),
    ('flex_nordica', 'Flexão Nórdica', 'pernas', 'corpo', 'avancado', 'pernas', ARRAY[]::TEXT[], 'pernas/Flexao Nordica.gif', 'Flexão nórdica.'),
    ('leg_press2', 'Leg Press', 'pernas', 'maquina', 'iniciante', 'pernas', ARRAY['glúteos'], 'pernas/Leg Press.gif', 'Leg press.'),
    ('leg_press_horiz', 'Leg Press Horizontal', 'pernas', 'maquina', 'iniciante', 'pernas', ARRAY['glúteos'], 'pernas/Leg Press Horizontal.gif', 'Leg press horizontal.'),
    ('leg_press_uni', 'Leg Press Unilateral', 'pernas', 'maquina', 'intermediario', 'pernas', ARRAY['glúteos'], 'pernas/Leg Press unilateral.gif', 'Leg press unilateral.'),
    ('lev_suporte', 'Levantamento com Suporte', 'pernas', 'maquina', 'intermediario', 'pernas', ARRAY['glúteos'], 'pernas/Levantamento com Suporte.gif', 'Levantamento suporte.'),
    ('lev_terra_alav', 'Levantamento Terra Alavanca', 'pernas', 'maquina', 'intermediario', 'pernas', ARRAY['costas', 'glúteos'], 'pernas/Levantamento Terra com Alavanca.gif', 'Terra alavanca.'),
    ('lev_terra_hex', 'Levantamento Terra Barra Hexagonal', 'pernas', 'barra', 'intermediario', 'pernas', ARRAY['costas', 'glúteos'], 'pernas/Levantamento Terra com Barra Hexagonal.gif', 'Terra barra hex.'),
    ('lev_terra_land', 'Levantamento Terra Landmine', 'pernas', 'barra', 'intermediario', 'pernas', ARRAY['costas', 'glúteos'], 'pernas/Levantamento Terra com Barra no Landmine.gif', 'Terra landmine.'),
    ('lev_terra_halt', 'Levantamento Terra Halteres', 'pernas', 'halteres', 'intermediario', 'pernas', ARRAY['costas', 'glúteos'], 'pernas/Levantamento Terra com Halteres.gif', 'Terra halteres.'),
    ('lev_terra_kettle', 'Levantamento Terra Kettlebell', 'pernas', 'kettlebell', 'intermediario', 'pernas', ARRAY['costas', 'glúteos'], 'pernas/Levantamento Terra com Kettlebell.gif', 'Terra kettlebell.'),
    ('lev_terra2', 'Levantamento Terra', 'pernas', 'barra', 'avancado', 'pernas', ARRAY['costas', 'glúteos'], 'pernas/Levantamento Terra.gif', 'Levantamento terra.'),
    ('lev_terra_rom_halt', 'Terra Romeno Halteres', 'pernas', 'halteres', 'intermediario', 'pernas', ARRAY['glúteos', 'lombar'], 'pernas/Levantamento terra romeno com halteres.gif', 'Terra romeno halteres.'),
    ('lev_terra_rom', 'Terra Romeno', 'pernas', 'barra', 'intermediario', 'pernas', ARRAY['glúteos', 'lombar'], 'pernas/Levantamento Terra Romeno.gif', 'Terra romeno.'),
    ('lev_terra_zercher', 'Terra Zercher', 'pernas', 'barra', 'avancado', 'pernas', ARRAY['core'], 'pernas/Levantamento Terra Zercher.gif', 'Terra zercher.'),
    ('mesa_flex2', 'Mesa Flexora', 'pernas', 'maquina', 'iniciante', 'pernas', ARRAY[]::TEXT[], 'pernas/Mesa flexora.gif', 'Mesa flexora.'),
    ('mesa_flex_uni', 'Mesa Flexora Unilateral', 'pernas', 'maquina', 'intermediario', 'pernas', ARRAY[]::TEXT[], 'pernas/Mesa Flexora Unilateral.gif', 'Mesa flexora unilateral.'),
    ('ponte_glut_barra', 'Ponte Glúteos Barra', 'pernas', 'barra', 'intermediario', 'pernas', ARRAY['glúteos'], 'pernas/Ponte de Gluteos com Barra.gif', 'Ponte glúteos barra.'),
    ('pressao_uni_alav', 'Pressão Unilateral Alavanca', 'pernas', 'maquina', 'intermediario', 'pernas', ARRAY['glúteos'], 'pernas/Pressao Unilateral Assistida por Alavanca.gif', 'Pressão unilateral alavanca.'),
    ('stiff2', 'Stiff com Barra', 'pernas', 'barra', 'intermediario', 'pernas', ARRAY['glúteos', 'lombar'], 'pernas/Stiff com barra.gif', 'Stiff barra.'),
    ('stiff_halt', 'Stiff com Halter', 'pernas', 'halteres', 'intermediario', 'pernas', ARRAY['glúteos', 'lombar'], 'pernas/Stiff com Halter.gif', 'Stiff halter.'),
    ('stiff_uni_barra', 'Stiff Unilateral Barra', 'pernas', 'barra', 'avancado', 'pernas', ARRAY['glúteos', 'lombar'], 'pernas/Stiff Unilateral com Barra.gif', 'Stiff unilateral barra.'),
    ('stiff_uni_halt', 'Stiff Unilateral Halteres', 'pernas', 'halteres', 'avancado', 'pernas', ARRAY['glúteos', 'lombar'], 'pernas/Stiff Unilateral com Halteres.gif', 'Stiff unilateral halteres.'),
    ('subida_step', 'Subida Step Elevação Joelhos', 'pernas', 'corpo', 'intermediario', 'pernas', ARRAY['glúteos'], 'pernas/Subida no Step com Elevacao de Joelhos.gif', 'Subida step joelhos.'),
    ('wall_sit', 'Wall Sit', 'pernas', 'corpo', 'iniciante', 'pernas', ARRAY[]::TEXT[], 'pernas/Wall Sit.gif', 'Wall sit.')
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, gif_path = EXCLUDED.gif_path, updated_at = NOW();

SELECT COUNT(*) as total_pernas FROM app_correcrat.exercises WHERE muscle_group_id = 'pernas';
