-- Exercícios de Costas baseados nos GIFs do Supabase Storage
INSERT INTO app_correcrat.exercises (id, name, muscle_group_id, equipment, difficulty, primary_muscle, secondary_muscles, gif_path, description) VALUES
    ('banco_romano', 'Banco Romano', 'costas', 'maquina', 'intermediario', 'costas', ARRAY['lombar'], 'Costas/banco romano.gif', 'Extensão de lombar no banco romano.'),
    ('banco_romano_sp', 'Banco Romano Sem Peso', 'costas', 'corpo', 'iniciante', 'costas', ARRAY['lombar'], 'Costas/banco romano sem peso.gif', 'Banco romano sem peso adicional.'),
    ('barra_fixa_assist', 'Barra Fixa Assistida', 'costas', 'maquina', 'iniciante', 'costas', ARRAY['bíceps'], 'Costas/Barra Fixa Assistida.gif', 'Barra fixa com auxílio.'),
    ('barra_fixa2', 'Barra Fixa', 'costas', 'corpo', 'avancado', 'costas', ARRAY['bíceps'], 'Costas/Barra fixa.gif', 'Barra fixa clássica.'),
    ('barra_livre_peso', 'Barra Livre com Peso', 'costas', 'barra', 'avancado', 'costas', ARRAY['bíceps'], 'Costas/barra livre com peso.gif', 'Barra fixa com peso adicional.'),
    ('barra_livre_aberta', 'Barra Livre Pegada Aberta', 'costas', 'corpo', 'avancado', 'costas', ARRAY['bíceps'], 'Costas/Barra Livre pegada aberta.gif', 'Barra fixa pegada aberta.'),
    ('barra_livre_flex', 'Barra Livre Joelhos Flexionados', 'costas', 'corpo', 'avancado', 'costas', ARRAY['bíceps'], 'Costas/barra livre pegada aberta joelhos flexionados.gif', 'Barra fixa com joelhos flexionados.'),
    ('barra_livre_cross', 'Barra Livre no Cross', 'costas', 'corpo', 'avancado', 'costas', ARRAY['bíceps'], 'Costas/barra livre pegada aberta no cross.gif', 'Barra fixa no cross.'),
    ('barra_fechada_pron', 'Barra Pegada Fechada Pronada', 'costas', 'corpo', 'avancado', 'costas', ARRAY['bíceps'], 'Costas/barra livre pegada fechada pronada.gif', 'Barra fixa fechada pronada.'),
    ('barra_pronada', 'Barra Pegada Pronada', 'costas', 'corpo', 'avancado', 'costas', ARRAY['bíceps'], 'Costas/barra livre pegada pronada.gif', 'Barra fixa pronada.'),
    ('barra_graviton', 'Barra no Graviton', 'costas', 'maquina', 'iniciante', 'costas', ARRAY['bíceps'], 'Costas/barra no gravitan.gif', 'Barra fixa assistida graviton.'),
    ('crucifixo_inv_costas', 'Crucifixo Inverso', 'costas', 'halteres', 'intermediario', 'costas', ARRAY['ombros'], 'Costas/crucifixo inverso.gif', 'Crucifixo inverso para costas.'),
    ('klimmzuege', 'Klimmzuege Obergriff', 'costas', 'corpo', 'avancado', 'costas', ARRAY['bíceps'], 'Costas/enge_klimmzuege_obergriff.gif', 'Pull up alemão.'),
    ('fitness_gifs', 'Fitness Gifs 4 U', 'costas', 'maquina', 'intermediario', 'costas', ARRAY['bíceps'], 'Costas/Fitness Gifs 4 U.gif', 'Exercício para costas.'),
    ('lev_terra2', 'Levantamento Terra', 'costas', 'barra', 'avancado', 'costas', ARRAY['glúteos', 'pernas'], 'Costas/Levantamento Terra.gif', 'Levantamento terra clássico.'),
    ('lev_terra_smith', 'Levantamento Terra Smith', 'costas', 'smith', 'intermediario', 'costas', ARRAY['glúteos'], 'Costas/levantamento terra no smith.gif', 'Levantamento terra no smith.'),
    ('lev_terra_romeno', 'Levantamento Terra Romeno', 'costas', 'barra', 'intermediario', 'costas', ARRAY['glúteos', 'lombar'], 'Costas/Levantamento Terra Romeno.gif', 'Terra romeno para posterior.'),
    ('pulldown_corda2', 'Pulldown com Corda', 'costas', 'cabo', 'intermediario', 'costas', ARRAY['bíceps'], 'Costas/Pulldown com corda.gif', 'Pulldown com corda.'),
    ('pulldown_incl_corda', 'Pulldown Inclinado Corda', 'costas', 'cabo', 'intermediario', 'costas', ARRAY['bíceps'], 'Costas/Pulldown inclinado com corda.gif', 'Pulldown inclinado com corda.'),
    ('pulldown_uni', 'Pulldown Unilateral', 'costas', 'cabo', 'intermediario', 'costas', ARRAY['bíceps'], 'Costas/Pulldown Unilateral no Cabo.gif', 'Pulldown unilateral.'),
    ('pulley_maquina', 'Pulley Costas Máquina', 'costas', 'maquina', 'iniciante', 'costas', ARRAY['bíceps'], 'Costas/pulley costa maquina.gif', 'Pulley na máquina.'),
    ('pulley_uni', 'Pulley Unilateral', 'costas', 'cabo', 'intermediario', 'costas', ARRAY['bíceps'], 'Costas/pulley costa unilateral.gif', 'Pulley unilateral.'),
    ('pulley_supinada', 'Pulley Frente Supinada', 'costas', 'cabo', 'intermediario', 'costas', ARRAY['bíceps'], 'Costas/pulley frente pegada supinada.gif', 'Pulley pegada supinada.'),
    ('pulley_fechada_pron', 'Pulley Fechada Pronada', 'costas', 'cabo', 'intermediario', 'costas', ARRAY['bíceps'], 'Costas/pulley frente pegaga fechda pronada.gif', 'Pulley fechada pronada.'),
    ('pulley_nuca', 'Pulley Atrás Nuca', 'costas', 'cabo', 'intermediario', 'costas', ARRAY['bíceps'], 'Costas/pulley pegada aberta atras da nuca.gif', 'Pulley por trás nuca.'),
    ('pulley_aberta', 'Pulley Pegada Aberta', 'costas', 'cabo', 'iniciante', 'costas', ARRAY['bíceps'], 'Costas/pulley pegada aberta.gif', 'Pulley pegada aberta.'),
    ('pulley_aberta_pron', 'Pulley Aberta Pronada', 'costas', 'cabo', 'intermediario', 'costas', ARRAY['bíceps'], 'Costas/pulley pegada aberta pronada.gif', 'Pulley aberta pronada.'),
    ('pullover_barra', 'Pullover com Barra', 'costas', 'barra', 'intermediario', 'costas', ARRAY['peitoral'], 'Costas/Pullover com Barra.gif', 'Pullover com barra.'),
    ('pullover_barra2', 'Pull Over com Barra', 'costas', 'barra', 'intermediario', 'costas', ARRAY['peitoral'], 'Costas/Pull Over com Barra.gif', 'Pullover barra variação.'),
    ('pullover_declinado', 'Pullover Banco Declinado', 'costas', 'barra', 'intermediario', 'costas', ARRAY['peitoral'], 'Costas/Pullover com barra no banco declinado.gif', 'Pullover no declinado.'),
    ('pullover_w_inv', 'Pullover Barra W Invertida', 'costas', 'barra', 'intermediario', 'costas', ARRAY['peitoral'], 'Costas/Pullover com Barra W Pegada invertida.gif', 'Pullover barra W invertida.'),
    ('pullover_cabo2', 'Pullover com Cabo', 'costas', 'cabo', 'intermediario', 'costas', ARRAY['peitoral'], 'Costas/Pullover com Cabo.gif', 'Pullover no cabo.'),
    ('pullover_cabo_sent', 'Pullover Cabo Sentado', 'costas', 'cabo', 'intermediario', 'costas', ARRAY['peitoral'], 'Costas/Pullover com cabo sentado.gif', 'Pullover cabo sentado.'),
    ('pullover_polia_corda', 'Pull Over Polia Corda', 'costas', 'cabo', 'intermediario', 'costas', ARRAY['peitoral'], 'Costas/Pull Over na polia com corda.gif', 'Pullover com corda.'),
    ('pull_up', 'Pull Up', 'costas', 'corpo', 'avancado', 'costas', ARRAY['bíceps'], 'Costas/Pull Up.gif', 'Pull up clássico.'),
    ('puxada_alavanca', 'Puxada Alta Alavanca', 'costas', 'maquina', 'intermediario', 'costas', ARRAY['bíceps'], 'Costas/Puxada Alta com Alavanca.gif', 'Puxada na alavanca.'),
    ('puxada_joelho', 'Puxada Joelho Apoiado', 'costas', 'cabo', 'intermediario', 'costas', ARRAY['bíceps'], 'Costas/Puxada Alta com Um Joelho Apoiado.gif', 'Puxada com joelho apoiado.'),
    ('puxada_alta2', 'Puxada Alta', 'costas', 'cabo', 'iniciante', 'costas', ARRAY['bíceps'], 'Costas/Puxada Alta.gif', 'Puxada alta clássica.'),
    ('puxada_invertida', 'Puxada Alta Invertida', 'costas', 'cabo', 'intermediario', 'costas', ARRAY['bíceps'], 'Costas/Puxada Alta Invertida.gif', 'Puxada supinada.'),
    ('puxada_nuca2', 'Puxada Nuca', 'costas', 'cabo', 'intermediario', 'costas', ARRAY['bíceps'], 'Costas/Puxada alta na polia nuca.gif', 'Puxada por trás nuca.'),
    ('puxada_ajoelhada', 'Puxada Unilateral Ajoelhada', 'costas', 'cabo', 'intermediario', 'costas', ARRAY['bíceps'], 'Costas/Puxada alta unilateral alta ajoelhada.gif', 'Puxada unilateral ajoelhada.'),
    ('puxada_maq', 'Puxada Máquina', 'costas', 'maquina', 'iniciante', 'costas', ARRAY['bíceps'], 'Costas/puxada maquina.gif', 'Puxada na máquina.'),
    ('puxada_maq_sup', 'Puxada Máquina Supinada', 'costas', 'maquina', 'intermediario', 'costas', ARRAY['bíceps'], 'Costas/puxada maquina pegada supinada.gif', 'Puxada máquina supinada.'),
    ('puxada_fechada', 'Puxada Pegada Fechada', 'costas', 'cabo', 'intermediario', 'costas', ARRAY['bíceps'], 'Costas/Puxada na Polia Alta com Pegada Fechada.gif', 'Puxada fechada.'),
    ('remada_incl_sup', 'Remada Inclinada Supinada', 'costas', 'halteres', 'intermediario', 'costas', ARRAY['bíceps'], 'Costas/remada aberta no banco inclinada pega supinada.gif', 'Remada inclinada supinada.'),
    ('remada_incl_halt', 'Remada Inclinada Halteres', 'costas', 'halteres', 'intermediario', 'costas', ARRAY['bíceps'], 'Costas/remada aberta no banco inclinado com halteres.gif', 'Remada inclinada halteres.'),
    ('remada_artic', 'Remada Articulada', 'costas', 'maquina', 'intermediario', 'costas', ARRAY['bíceps'], 'Costas/remada articulada.gif', 'Remada articulada.'),
    ('remada_artic_sup', 'Remada Articulada Supinada', 'costas', 'maquina', 'intermediario', 'costas', ARRAY['bíceps'], 'Costas/remada articulada pegada supinada.gif', 'Remada articulada supinada.'),
    ('remada_baixa_sup', 'Remada Baixa Supinada', 'costas', 'cabo', 'intermediario', 'costas', ARRAY['bíceps'], 'Costas/remada baixa no pulley pegada aberta supinada.gif', 'Remada baixa supinada.'),
    ('remada_baixa_uni', 'Remada Baixa Unilateral', 'costas', 'cabo', 'intermediario', 'costas', ARRAY['bíceps'], 'Costas/remada baixa unilateral no cross.gif', 'Remada baixa unilateral.'),
    ('remada_baixa_neutra', 'Remada Baixa Neutra', 'costas', 'cabo', 'intermediario', 'costas', ARRAY['bíceps'], 'Costas/remada baixa unilateral pegada neutra.gif', 'Remada baixa pegada neutra.'),
    ('remada_triangulo', 'Remada Triângulo', 'costas', 'cabo', 'intermediario', 'costas', ARRAY['bíceps'], 'Costas/remada beixa no pulley triangulo.gif', 'Remada com triângulo.'),
    ('remada_cav_aberta', 'Remada Cavalinho Aberta', 'costas', 'barra', 'intermediario', 'costas', ARRAY['bíceps'], 'Costas/remada cavalinha pegada aberta.gif', 'Remada cavalinho aberta.'),
    ('remada_cav_uni', 'Remada Cavalinho Unilateral', 'costas', 'barra', 'intermediario', 'costas', ARRAY['bíceps'], 'Costas/remada cavalinho unilateral.gif', 'Remada cavalinho unilateral.'),
    ('remada_cav_barra', 'Remada Cavalinho Barra', 'costas', 'barra', 'intermediario', 'costas', ARRAY['bíceps'], 'Costas/remada cavalino com barra.gif', 'Remada cavalinho com barra.'),
    ('remada_incl_halt2', 'Remada Banco Inclinado Halteres', 'costas', 'halteres', 'intermediario', 'costas', ARRAY['bíceps'], 'Costas/remada com banco inclinado com haltres.gif', 'Remada no banco inclinado.'),
    ('remada_barra', 'Remada com Barra', 'costas', 'barra', 'intermediario', 'costas', ARRAY['bíceps'], 'Costas/remada com barra.gif', 'Remada curvada com barra.'),
    ('remada_cruzada', 'Remada Cruzada Cross', 'costas', 'cabo', 'intermediario', 'costas', ARRAY['bíceps'], 'Costas/Remada cruzada no cross.gif', 'Remada cruzada no cross.'),
    ('remada_curvada2', 'Remada Curvada Barra', 'costas', 'barra', 'intermediario', 'costas', ARRAY['bíceps', 'lombar'], 'Costas/Remada Curvada com Barra.gif', 'Remada curvada clássica.'),
    ('remada_curv_inv', 'Remada Curvada Invertida', 'costas', 'halteres', 'intermediario', 'costas', ARRAY['bíceps'], 'Costas/Remada curvada com halteres com pegada invertida.gif', 'Remada curvada invertida.'),
    ('remada_curv_halt', 'Remada Curvada Halteres', 'costas', 'halteres', 'intermediario', 'costas', ARRAY['bíceps'], 'Costas/Remada curvada com halteres.gif', 'Remada curvada halteres.'),
    ('remada_kettlebell', 'Remada Curvada Kettlebell', 'costas', 'kettlebell', 'intermediario', 'costas', ARRAY['bíceps'], 'Costas/Remada curvada com kettlebell.gif', 'Remada com kettlebell.'),
    ('remada_curv_inv_bar', 'Remada Curvada Invertida Barra', 'costas', 'barra', 'intermediario', 'costas', ARRAY['bíceps'], 'Costas/Remada Curvada com Pegada Invertida na Barra.gif', 'Remada curvada invertida barra.'),
    ('remada_t', 'Remada Curvada em T', 'costas', 'barra', 'intermediario', 'costas', ARRAY['bíceps'], 'Costas/Remada Curvada em T.gif', 'Remada T.'),
    ('remada_curv_incl', 'Remada Curvada Inclinada', 'costas', 'barra', 'intermediario', 'costas', ARRAY['bíceps'], 'Costas/Remada Curvada Inclinada com Barra.gif', 'Remada curvada inclinada.'),
    ('remada_curv_smith', 'Remada Curvada Smith', 'costas', 'smith', 'intermediario', 'costas', ARRAY['bíceps'], 'Costas/Remada Curvada no Smith.gif', 'Remada curvada no smith.'),
    ('remada_espingarda', 'Remada de Espingarda', 'costas', 'barra', 'intermediario', 'costas', ARRAY['bíceps'], 'Costas/Remada de espingarda.gif', 'Remada espingarda.'),
    ('remada_frontal_alav', 'Remada Frontal Alavanca', 'costas', 'maquina', 'intermediario', 'costas', ARRAY['bíceps'], 'Costas/Remada frontal com alavanca.gif', 'Remada frontal alavanca.'),
    ('remada_incl_cabo', 'Remada Inclinada Cabo', 'costas', 'cabo', 'intermediario', 'costas', ARRAY['bíceps'], 'Costas/Remada Inclinada com Cabo.gif', 'Remada inclinada cabo.'),
    ('remada_incl_neutra', 'Remada Inclinada Neutra', 'costas', 'halteres', 'intermediario', 'costas', ARRAY['bíceps'], 'Costas/Remada Inclinada com Pegada Neutra com Halteres.gif', 'Remada inclinada neutra.'),
    ('remada_incl_reversa', 'Remada Inclinada Reversa', 'costas', 'halteres', 'intermediario', 'costas', ARRAY['bíceps'], 'Costas/Remada Inclinada com Pegada Reversa com Halteres.gif', 'Remada inclinada reversa.'),
    ('remada_incl_banco_cabo', 'Remada Inclinada Banco Cabo', 'costas', 'cabo', 'intermediario', 'costas', ARRAY['bíceps'], 'Costas/Remada Inclinada no banco com Cabo.gif', 'Remada inclinada banco cabo.'),
    ('remada_incl_smith', 'Remada Inclinada Smith', 'costas', 'smith', 'intermediario', 'costas', ARRAY['bíceps'], 'Costas/remada inclinada no smith.gif', 'Remada inclinada smith.'),
    ('remada_incl_sup_fech', 'Remada Inclinada Supinada Fechada', 'costas', 'cabo', 'intermediario', 'costas', ARRAY['bíceps'], 'Costas/remada inclinda no banco pegada supinda puxada fechada.gif', 'Remada inclinada supinada fechada.'),
    ('remada_invertida', 'Remada Invertida', 'costas', 'corpo', 'intermediario', 'costas', ARRAY['bíceps'], 'Costas/Remada Invertida.gif', 'Remada invertida corpo.'),
    ('remada_livre_halt', 'Remada Livre Halteres', 'costas', 'halteres', 'intermediario', 'costas', ARRAY['bíceps'], 'Costas/remada livre  com halteres.gif', 'Remada livre halteres.'),
    ('remada_maq_pron', 'Remada Máquina Pronada', 'costas', 'maquina', 'intermediario', 'costas', ARRAY['bíceps'], 'Costas/remada maquina pronada.gif', 'Remada máquina pronada.'),
    ('remada_incl_pron_bar', 'Remada Inclinada Pronada Barra', 'costas', 'barra', 'intermediario', 'costas', ARRAY['bíceps'], 'Costas/remada no banco inclinado pegada pronada com barra.gif', 'Remada inclinada pronada barra.'),
    ('remada_renegada', 'Remada Renegada', 'costas', 'halteres', 'avancado', 'costas', ARRAY['core'], 'Costas/Remada Renegada com Halteres.gif', 'Remada renegada.'),
    ('remada_sent_anilhas', 'Remada Sentada Anilhas', 'costas', 'anilha', 'intermediario', 'costas', ARRAY['bíceps'], 'Costas/Remada Sentada com Anilhas.gif', 'Remada sentada anilhas.'),
    ('remada_sent_cabo', 'Remada Sentada Cabo', 'costas', 'cabo', 'iniciante', 'costas', ARRAY['bíceps'], 'Costas/Remada Sentada com Cabo.gif', 'Remada sentada cabo.'),
    ('remada_sent_corda', 'Remada Sentada Corda', 'costas', 'cabo', 'intermediario', 'costas', ARRAY['bíceps'], 'Costas/Remada Sentada com Corda na Polia.gif', 'Remada sentada corda.'),
    ('remada_sent_fechada', 'Remada Sentada Fechada', 'costas', 'cabo', 'intermediario', 'costas', ARRAY['bíceps'], 'Costas/Remada sentado com cabo pegada fechada.gif', 'Remada sentada fechada.'),
    ('remada_serrote2', 'Remada Serrote', 'costas', 'halteres', 'intermediario', 'costas', ARRAY['bíceps'], 'Costas/remada serrote.gif', 'Remada serrote clássica.'),
    ('remada_t_alav', 'Remada T Alavanca', 'costas', 'maquina', 'intermediario', 'costas', ARRAY['bíceps'], 'Costas/Remada T com alavanca.gif', 'Remada T alavanca.'),
    ('remada_t_landmine', 'Remada T Landmine', 'costas', 'barra', 'intermediario', 'costas', ARRAY['bíceps'], 'Costas/Remada T com Landmine.gif', 'Remada T landmine.'),
    ('remada_t_inv', 'Remada T Invertida', 'costas', 'maquina', 'intermediario', 'costas', ARRAY['bíceps'], 'Costas/Remada T invertida com alavanca.gif', 'Remada T invertida.'),
    ('remada_uni_cav', 'Remada Unilateral Cavalinho', 'costas', 'barra', 'intermediario', 'costas', ARRAY['bíceps'], 'Costas/remada unilateral cavalindo barra puxada fechada.gif', 'Remada unilateral cavalinho.'),
    ('remada_uni_barra', 'Remada Unilateral Barra', 'costas', 'barra', 'intermediario', 'costas', ARRAY['bíceps'], 'Costas/Remada Unilateral com Barra.gif', 'Remada unilateral barra.'),
    ('remada_uni_landmine', 'Remada Unilateral Landmine', 'costas', 'barra', 'intermediario', 'costas', ARRAY['bíceps'], 'Costas/Remada unilateral com barra landmine.gif', 'Remada unilateral landmine.'),
    ('remada_uni_cabo', 'Remada Unilateral Cabo', 'costas', 'cabo', 'intermediario', 'costas', ARRAY['bíceps'], 'Costas/Remada Unilateral com Cabo.gif', 'Remada unilateral cabo.'),
    ('remada_curv_barra2', 'Remada Curvada Barra 2', 'costas', 'barra', 'intermediario', 'costas', ARRAY['bíceps'], 'Costas/Remanda Curvada Barra.gif', 'Remada curvada barra variação.'),
    ('remada_uni_banco', 'Remada Unilateral Apoio Banco', 'costas', 'halteres', 'intermediario', 'costas', ARRAY['bíceps'], 'Costas/Remanda unil com apoio banco.gif', 'Remada unilateral apoio banco.'),
    ('remo_barra_punho', 'Remo Barra no Punho', 'costas', 'barra', 'avancado', 'costas', ARRAY['antebraço'], 'Costas/Remo com barra no punho.gif', 'Remo barra no punho.'),
    ('serrote2', 'Serrote', 'costas', 'halteres', 'intermediario', 'costas', ARRAY['bíceps'], 'Costas/Serrote.gif', 'Serrote clássico.'),
    ('superman', 'Superman', 'costas', 'corpo', 'iniciante', 'costas', ARRAY['lombar'], 'Costas/superman.gif', 'Superman para lombar.'),
    ('voador_inv_costas', 'Voador Invertido', 'costas', 'maquina', 'iniciante', 'costas', ARRAY['ombros'], 'Costas/voador invertido.gif', 'Voador invertido para costas.')
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, gif_path = EXCLUDED.gif_path, updated_at = NOW();

SELECT COUNT(*) as total_costas FROM app_correcrat.exercises WHERE muscle_group_id = 'costas';
