-- Exercícios de Tríceps baseados nos GIFs do Supabase Storage
INSERT INTO app_correcrat.exercises (id, name, muscle_group_id, equipment, difficulty, primary_muscle, secondary_muscles, gif_path, description) VALUES
    ('apoio_fechado_parede', 'Apoio Frente Pegada Fechada Parede', 'triceps', 'corpo', 'iniciante', 'tríceps', ARRAY['peitoral'], 'triceps/Apoio de frente pegada fechada parede.gif', 'Flexão fechada na parede.'),
    ('dips_maquina', 'Dips Máquina Arnold', 'triceps', 'maquina', 'intermediario', 'tríceps', ARRAY['peitoral'], 'triceps/arnold_dips-maschine.gif', 'Dips na máquina.'),
    ('ext_conc_cabo_joelho', 'Extensão Concentrada Cabo Joelho', 'triceps', 'cabo', 'intermediario', 'tríceps', ARRAY[]::TEXT[], 'triceps/Extensao Concentrada com Cabo no Joelho.gif', 'Extensão concentrada joelho.'),
    ('ext_cabo_incl', 'Extensão Tríceps Cabo Inclinado', 'triceps', 'cabo', 'intermediario', 'tríceps', ARRAY[]::TEXT[], 'triceps/Extensao de triceps com cabo inclinado.gif', 'Extensão inclinada cabo.'),
    ('flex_cotovelo_fechado', 'Flexão Cotovelo Fechado', 'triceps', 'corpo', 'intermediario', 'tríceps', ARRAY['peitoral'], 'triceps/flex de cotovelo fechado.gif', 'Flexão cotovelo fechado.'),
    ('flex_cotovelo_halt', 'Flexão Cotovelo Fechado Halteres', 'triceps', 'halteres', 'intermediario', 'tríceps', ARRAY['peitoral'], 'triceps/flex de cotovelo fechado com halteres.gif', 'Flexão fechada halteres.'),
    ('flex_cotovelo_livre', 'Flexão Cotovelo Fechado Livre', 'triceps', 'corpo', 'intermediario', 'tríceps', ARRAY['peitoral'], 'triceps/flex de cotovelo fechado livre.gif', 'Flexão cotovelo livre.'),
    ('kickback', 'Kick Back', 'triceps', 'halteres', 'intermediario', 'tríceps', ARRAY[]::TEXT[], 'triceps/Kick back.gif', 'Kick back tríceps.'),
    ('kickback_sent', 'Kick Back Sentado Halteres', 'triceps', 'halteres', 'intermediario', 'tríceps', ARRAY[]::TEXT[], 'triceps/Kick back sentado com halteres.gif', 'Kick back sentado.'),
    ('supino_decl_smith', 'Supino Declinado Smith', 'triceps', 'smith', 'intermediario', 'tríceps', ARRAY['peitoral'], 'triceps/supino declinado no smit.gif', 'Supino declinado smith.'),
    ('supino_decl_fechado', 'Supino Declinado Pegada Fechada', 'triceps', 'barra', 'intermediario', 'tríceps', ARRAY['peitoral'], 'triceps/Supino declinado pegada fechada.gif', 'Supino declinado fechada.'),
    ('supino_fechado2', 'Supino Fechado', 'triceps', 'barra', 'intermediario', 'tríceps', ARRAY['peitoral'], 'triceps/Supino Fechado.gif', 'Supino fechado clássico.'),
    ('supino_inv_fechado', 'Supino Invertido Pegada Fechada', 'triceps', 'barra', 'intermediario', 'tríceps', ARRAY['peitoral'], 'triceps/Supino Invertido com Pegada Fechada.gif', 'Supino invertido fechado.'),
    ('supino_pegada_fechada', 'Supino Pegada Fechada', 'triceps', 'barra', 'intermediario', 'tríceps', ARRAY['peitoral'], 'triceps/Supino pegada fechada.gif', 'Supino pegada fechada.'),
    ('triceps_basico', 'Tríceps', 'triceps', 'cabo', 'iniciante', 'tríceps', ARRAY[]::TEXT[], 'triceps/triceps.gif', 'Tríceps básico.'),
    ('triceps_afundo_banco', 'Tríceps Afundo no Banco', 'triceps', 'corpo', 'iniciante', 'tríceps', ARRAY['ombros'], 'triceps/triceps afundo no banco.gif', 'Tríceps banco.'),
    ('triceps_apoio_parede', 'Tríceps Apoiado na Parede', 'triceps', 'corpo', 'iniciante', 'tríceps', ARRAY[]::TEXT[], 'triceps/triceps apoaiado na pareda.gif', 'Tríceps parede.'),
    ('triceps_barra_cross', 'Tríceps Barra Cross', 'triceps', 'cabo', 'iniciante', 'tríceps', ARRAY[]::TEXT[], 'triceps/TRICEPS-BARRA-CROSS.gif', 'Tríceps barra cross.'),
    ('triceps_halt_banco', 'Tríceps Halteres Banco Reto', 'triceps', 'halteres', 'intermediario', 'tríceps', ARRAY[]::TEXT[], 'triceps/triceps com halteres no banco reto.gif', 'Tríceps halteres banco.'),
    ('triceps_frances_w', 'Tríceps Francês Barra W', 'triceps', 'barra', 'intermediario', 'tríceps', ARRAY[]::TEXT[], 'triceps/Triceps frances barra W.gif', 'Tríceps francês barra W.'),
    ('triceps_incl_cross', 'Tríceps Inclinado Cross Bilateral', 'triceps', 'cabo', 'intermediario', 'tríceps', ARRAY[]::TEXT[], 'triceps/triceps inclinado no cross bilateral.gif', 'Tríceps inclinado cross.'),
    ('triceps_paralela_maq', 'Tríceps Paralela Máquina', 'triceps', 'maquina', 'intermediario', 'tríceps', ARRAY['peitoral'], 'triceps/triceps na paralela maquiba.gif', 'Tríceps paralela máquina.'),
    ('triceps_scott', 'Tríceps Aparelho Scott', 'triceps', 'maquina', 'intermediario', 'tríceps', ARRAY[]::TEXT[], 'triceps/triceps no aparelho scort.gif', 'Tríceps scott.'),
    ('triceps_triangulo', 'Tríceps Cross Barra Triângulo', 'triceps', 'cabo', 'intermediario', 'tríceps', ARRAY[]::TEXT[], 'triceps/triceps no cross barra triangulo.gif', 'Tríceps triângulo.'),
    ('triceps_cross_deitado', 'Tríceps Cross Deitado Banco', 'triceps', 'cabo', 'intermediario', 'tríceps', ARRAY[]::TEXT[], 'triceps/triceps no cross deitado no banco reto.gif', 'Tríceps cross deitado.'),
    ('triceps_paralelo_banco', 'Tríceps Paralelo Banco', 'triceps', 'corpo', 'iniciante', 'tríceps', ARRAY['ombros'], 'triceps/triceps paralelo no banco.gif', 'Tríceps paralelo banco.'),
    ('triceps_patada_bi', 'Tríceps Patada Bilateral Halteres', 'triceps', 'halteres', 'intermediario', 'tríceps', ARRAY[]::TEXT[], 'triceps/triceps patada blateral com halteres.gif', 'Tríceps patada bilateral.'),
    ('triceps_patada_uni', 'Tríceps Patada Unilateral Halteres', 'triceps', 'halteres', 'intermediario', 'tríceps', ARRAY[]::TEXT[], 'triceps/triceps patada unilateral com halteres.gif', 'Tríceps patada unilateral.'),
    ('triceps_patada_halt', 'Tríceps Patada Halteres', 'triceps', 'halteres', 'intermediario', 'tríceps', ARRAY[]::TEXT[], 'triceps/triceps pateda com alteres.gif', 'Tríceps patada.'),
    ('triceps_pron_uni', 'Tríceps Pronada Unilateral Cross', 'triceps', 'cabo', 'intermediario', 'tríceps', ARRAY[]::TEXT[], 'triceps/triceps pegada pronada uniatres no cross.gif', 'Tríceps pronada unilateral.'),
    ('triceps_pulley_corda2', 'Tríceps Pulley Corda', 'triceps', 'cabo', 'iniciante', 'tríceps', ARRAY[]::TEXT[], 'triceps/Triceps-Pulley-Corda.gif', 'Tríceps pulley corda.'),
    ('triceps_testa_barra2', 'Tríceps Testa Barra', 'triceps', 'barra', 'intermediario', 'tríceps', ARRAY[]::TEXT[], 'triceps/triceps testa com barra.gif', 'Tríceps testa barra.'),
    ('triceps_testa_halt2', 'Tríceps Testa Halteres', 'triceps', 'halteres', 'intermediario', 'tríceps', ARRAY[]::TEXT[], 'triceps/Triceps testa com halteres.gif', 'Tríceps testa halteres.'),
    ('triceps_testa_neutra', 'Tríceps Testa Pegada Neutra', 'triceps', 'halteres', 'intermediario', 'tríceps', ARRAY[]::TEXT[], 'triceps/triceps testa pegada neutra deitado no banco.gif', 'Tríceps testa neutra.'),
    ('triceps_testa_halt3', 'Tríceps Testa Halteres 2', 'triceps', 'halteres', 'intermediario', 'tríceps', ARRAY[]::TEXT[], 'triceps/triceps tresta com halteres.gif', 'Tríceps testa variação.'),
    ('triceps_uni_90g', 'Tríceps Unilateral 90G Deitado', 'triceps', 'halteres', 'intermediario', 'tríceps', ARRAY[]::TEXT[], 'triceps/triceps unilateral 90G deitado.gif', 'Tríceps unilateral 90G.'),
    ('triceps_uni_deitado', 'Tríceps Unilateral Deitado Banco', 'triceps', 'halteres', 'intermediario', 'tríceps', ARRAY[]::TEXT[], 'triceps/triceps unilateral deitado no banco.gif', 'Tríceps unilateral deitado.'),
    ('triceps_uni_supinada', 'Tríceps Unilateral Pegada Supinada', 'triceps', 'cabo', 'intermediario', 'tríceps', ARRAY[]::TEXT[], 'triceps/triceps unilateral pegada supinada.gif', 'Tríceps unilateral supinada.')
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name, gif_path = EXCLUDED.gif_path, updated_at = NOW();

SELECT COUNT(*) as total_triceps FROM app_correcrat.exercises WHERE muscle_group_id = 'triceps';
